cancer_keywords = [
    word.lower()
    for word in [
        # AIDS-Related Lymphoma
        "Lymphoma, AIDS Related",
        "Lymphoma, HIV-Related",
        "Lymphoma, HIV Related",
        "HIV-Related Lymphoma",
        "HIV Related Lymphoma",
        "HIV-Related Lymphomas",
        "Lymphomas, HIV-Related",
        "Lymphoma, AIDS-Associated",
        "AIDS-Associated Lymphomas",
        "Lymphoma, AIDS Associated",
        "Lymphomas, AIDS-Associated",
        "AIDS-Associated Lymphoma",
        "AIDS Associated Lymphoma",
        "AIDS-Related Lymphoma",
        "AIDS Related Lymphoma",
        "AIDS-Related Lymphomas",
        "Lymphomas, AIDS-Related"
        # eye neoplasms
        "Eye Neoplasm",
        "Neoplasm, Eye",
        "Neoplasms, Eye",
        "Cancer of Eye",
        "Eye Cancers",
        "Cancer of the Eye",
        "Eye Cancer",
        "Cancer, Eye",
        "Cancers, Eye",
        "Conjunctival Neoplasms",
        "Intraocular Lymphoma",
        "Orbital Neoplasms",
        "Paraneoplastic Syndromes, Ocular",
        "Retinal Neoplasms",
        "Retinoblastoma",
        "Uveal Neoplasms",
        "Choroid Neoplasms",
        "Iris Neoplasms",
        # Wilms Tumor and Other Childhood Kidney Tumors
        "Tumor, Wilms",
        "Wilms' Tumor",
        "Tumor, Wilms'",
        "Wilm Tumor",
        "Wilm's Tumor",
        "Wilms Tumor 1",
        "Nephroblastoma",
        "Nephroblastomas",
        "Bilateral Wilms Tumor",
        "Tumor, Bilateral Wilms",
        "Wilms Tumor, Bilateral",
        "Denys-Drash Syndrome",
        "WAGR Syndrome",
        # Ovarian Tumors
        "Carcinoma, Ovarian Epithelial",
        "Granulosa Cell Tumor",
        "Hereditary Breast and Ovarian Cancer Syndrome",
        "Luteoma",
        "Meigs Syndrome",
        "Sertoli-Leydig Cell Tumor",
        "Thecoma",
        "Krukenberg Tumor",
        "Brenner Tumor",
        # Primary Peritoneal Cancer
        "Neoplasm, Peritoneal",
        "Peritoneal Neoplasm",
        "Peritoneal Surface Malignancy",
        "Malignancy, Peritoneal Surface",
        "Peritoneal Surface Malignancies",
        "Surface Malignancy, Peritoneal",
        "Peritoneal Carcinomatosis",
        "Carcinomatosis, Peritoneal",
        "Peritoneal Carcinomatoses",
        "Pseudomyxoma Peritonei",
        # Vaginal Cancer
        "Neoplasm, Vaginal",
        "Vaginal Neoplasm",
        "Vagina Neoplasms",
        "Neoplasm, Vagina",
        "Neoplasms, Vagina",
        "Vagina Neoplasm",
        "Neoplasms, Vaginal",
        "Vaginal Cancer",
        "Cancer, Vaginal",
        "Cancers, Vaginal",
        "Vaginal Cancers",
        "Cancer of the Vagina",
        "Cancer of Vagina",
        "Vagina Cancers",
        "Vagina Cancer",
        "Cancer, Vagina",
        "Cancers, Vagina",
        # Vulvar Cancer
        "Neoplasm, Vulvar",
        "Vulvar Neoplasm",
        "Vulva Neoplasms",
        "Neoplasm, Vulva",
        "Neoplasms, Vulva",
        "Vulva Neoplasm",
        "Neoplasms, Vulvar",
        "Cancer of Vulva",
        "Vulva Cancers",
        "Cancer of the Vulva",
        "Vulva Cancer",
        "Cancer, Vulva",
        "Cancers, Vulva",
        "Vulvar Cancer",
        "Cancer, Vulvar",
        "Cancers, Vulvar",
        "Vulvar Cancers",
        # head and neck neoplasms
        "Neoplasms, Head and Neck",
        "Head, Neck Neoplasms",
        "Head and Neck Neoplasm",
        "Cancer of Head and Neck",
        "Head and Neck Cancer",
        "Cancer of the Head and Neck",
        "Upper Aerodigestive Tract Neoplasms",
        "UADT Neoplasm",
        "Neoplasm, UADT",
        "Neoplasms, UADT",
        "UADT Neoplasms",
        "Neoplasms, Upper Aerodigestive Tract",
        "Upper Aerodigestive Tract Neoplasm",
        "Head Neoplasms",
        "Neoplasms, Head",
        "Head Neoplasm",
        "Neoplasm, Head",
        "Neck Neoplasms",
        "Neoplasms, Neck",
        "Neck Neoplasm",
        "Neoplasm, Neck",
        "Cancer of Head",
        "Head Cancers",
        "Head Cancer",
        "Cancer, Head",
        "Cancers, Head",
        "Cancer of the Head",
        "Cancer of Neck",
        "Neck Cancers",
        "Neck Cancer",
        "Cancer, Neck",
        "Cancers, Neck",
        "Cancer of the Neck",
        "Esophageal Neoplasm",
        "Neoplasm, Esophageal",
        "Esophagus Neoplasm",
        "Esophagus Neoplasms",
        "Neoplasm, Esophagus",
        "Neoplasms, Esophagus",
        "Neoplasms, Esophageal",
        "Cancer of Esophagus",
        "Cancer of the Esophagus",
        "Esophagus Cancer",
        "Cancer, Esophagus",
        "Cancers, Esophagus",
        "Esophagus Cancers",
        "Esophageal Cancer",
        "Cancer, Esophageal",
        "Cancers, Esophageal",
        "Esophageal Cancers",
        "Esophageal Squamous Cell Carcinoma",
        "Facial Neoplasm",
        "Neoplasm, Facial",
        "Neoplasms, Facial",
        "Eyelid Neoplasm",
        "Neoplasm, Eyelid",
        "Neoplasms, Eyelid",
        "Mouth Neoplasm",
        "Neoplasm, Mouth",
        "Neoplasms, Oral",
        "Neoplasm, Oral",
        "Oral Neoplasm",
        "Oral Neoplasms",
        "Neoplasms, Mouth",
        "Cancer of Mouth",
        "Mouth Cancers",
        "Oral Cancer",
        "Cancer, Oral",
        "Cancers, Oral",
        "Oral Cancers",
        "Cancer of the Mouth",
        "Mouth Cancer",
        "Cancer, Mouth",
        "Cancers, Mouth",
        "Neoplasms, Gingival",
        "Gingival Neoplasm",
        "Neoplasm, Gingival",
        "Congenital Epulides",
        "Epulides, Congenital",
        "Epulis, Congenital",
        "Congenital Epulis",
        "Leukoplakias, Oral",
        "Oral Leukoplakia",
        "Oral Leukoplakias",
        "Leukokeratosis, Oral",
        "Leukokeratoses, Oral",
        "Oral Leukokeratoses",
        "Oral Leukokeratosis",
        "Keratosis, Oral",
        "Keratoses, Oral",
        "Oral Keratoses",
        "Oral Keratosis",
        "Lip Neoplasm",
        "Neoplasm, Lip",
        "Neoplasms, Lip",
        "Cancer of Lip",
        "Lip Cancers",
        "Cancer of the Lip",
        "Lip Cancer",
        "Cancer, Lip",
        "Cancers, Lip",
        "Neoplasm, Palatal",
        # Oropharyngeal Cancer
        "Neoplasm, Oropharyngeal",
        "Oropharyngeal Neoplasm",
        "Oropharynx Neoplasms",
        "Neoplasm, Oropharynx",
        "Neoplasms, Oropharynx",
        "Oropharynx Neoplasm",
        "Neoplasms, Oropharyngeal",
        "Cancer of Oropharnyx",
        "Oropharnyx Cancer",
        "Oropharnyx Cancers",
        "Oropharyngeal Cancer",
        "Cancer, Oropharyngeal",
        "Cancers, Oropharyngeal",
        "Oropharyngeal Cancers",
        "Oropharynx Cancer",
        "Cancer, Oropharynx",
        "Cancers, Oropharynx",
        "Oropharynx Cancers",
        "Cancer of the Oropharynx",
        "Tonsil Neoplasms",
        "Neoplasms, Tonsil",
        "Neoplasm, Tonsil",
        "Tonsil Neoplasm",
        "Neoplasms, Tonsillar",
        "Neoplasm, Tonsillar",
        "Tonsillar Neoplasm",
        "Cancer of Tonsil",
        "Tonsil Cancers",
        "Cancer of the Tonsil",
        "Tonsil Cancer",
        "Cancer, Tonsil",
        "Cancers, Tonsil",
        "Tonsillar Cancer",
        "Cancer, Tonsillar",
        "Cancers, Tonsillar",
        "Tonsillar Cancers",
        # head and neck neoplasms
        "Neoplasms, Head and Neck",
        "Head, Neck Neoplasms",
        "Head and Neck Neoplasm",
        "Cancer of Head and Neck",
        "Head and Neck Cancer",
        "Cancer of the Head and Neck",
        "Upper Aerodigestive Tract Neoplasms",
        "UADT Neoplasm",
        "Neoplasm, UADT",
        "Neoplasms, UADT",
        "UADT Neoplasms",
        "Neoplasms, Upper Aerodigestive Tract",
        "Upper Aerodigestive Tract Neoplasm",
        "Head Neoplasms",
        "Neoplasms, Head",
        "Head Neoplasm",
        "Neoplasm, Head",
        "Neck Neoplasms",
        "Neoplasms, Neck",
        "Neck Neoplasm",
        "Neoplasm, Neck",
        "Cancer of Head",
        "Head Cancers",
        "Head Cancer",
        "Cancer, Head",
        "Cancers, Head",
        "Cancer of the Head",
        "Cancer of Neck",
        "Neck Cancers",
        "Neck Cancer",
        "Cancer, Neck",
        "Cancers, Neck",
        "Cancer of the Neck",
        "Esophageal Neoplasm",
        "Neoplasm, Esophageal",
        "Esophagus Neoplasm",
        "Esophagus Neoplasms",
        "Neoplasm, Esophagus",
        "Neoplasms, Esophagus",
        "Neoplasms, Esophageal",
        "Cancer of Esophagus",
        "Cancer of the Esophagus",
        "Esophagus Cancer",
        "Cancer, Esophagus",
        "Cancers, Esophagus",
        "Esophagus Cancers",
        "Esophageal Cancer",
        "Cancer, Esophageal",
        "Cancers, Esophageal",
        "Esophageal Cancers",
        "Esophageal Squamous Cell Carcinoma",
        "Facial Neoplasm",
        "Neoplasm, Facial",
        "Neoplasms, Facial",
        "Eyelid Neoplasm",
        "Neoplasm, Eyelid",
        "Neoplasms, Eyelid",
        "Mouth Neoplasm",
        "Neoplasm, Mouth",
        "Neoplasms, Oral",
        "Neoplasm, Oral",
        "Oral Neoplasm",
        "Oral Neoplasms",
        "Neoplasms, Mouth",
        "Cancer of Mouth",
        "Mouth Cancers",
        "Oral Cancer",
        "Cancer, Oral",
        "Cancers, Oral",
        "Oral Cancers",
        "Cancer of the Mouth",
        "Mouth Cancer",
        "Cancer, Mouth",
        "Cancers, Mouth",
        "Neoplasms, Gingival",
        "Gingival Neoplasm",
        "Neoplasm, Gingival",
        "Congenital Epulides",
        "Epulides, Congenital",
        "Epulis, Congenital",
        "Congenital Epulis",
        "Leukoplakias, Oral",
        "Oral Leukoplakia",
        "Oral Leukoplakias",
        "Leukokeratosis, Oral",
        "Leukokeratoses, Oral",
        "Oral Leukokeratoses",
        "Oral Leukokeratosis",
        "Keratosis, Oral",
        "Keratoses, Oral",
        "Oral Keratoses",
        "Oral Keratosis",
        "Lip Neoplasm",
        "Neoplasm, Lip",
        "Neoplasms, Lip",
        "Cancer of Lip",
        "Lip Cancers",
        "Cancer of the Lip",
        "Lip Cancer",
        "Cancer, Lip",
        "Cancers, Lip",
        "Neoplasm, Palatal",
        # include salivary glands below
        "Neoplasm, Tongue",
        "Tongue Neoplasm",
        "Neoplasms, Tongue",
        "Cancer of Tongue",
        "Tongue Cancers",
        "Cancer of the Tongue",
        "Tongue Cancer",
        "Cancer, Tongue",
        "Cancers, Tongue",
        "Neoplasm, Otorhinolaryngologic",
        "Otorhinolaryngologic Neoplasm",
        "Ootorhinolaryngeal Neoplasms",
        "Neoplasm, Ootorhinolaryngeal",
        "Neoplasms, Ootorhinolaryngeal",
        "Ootorhinolaryngeal Neoplasm",
        "Neoplasms, Otorhinolaryngological",
        "Neoplasm, Otorhinolaryngological",
        "Otorhinolaryngological Neoplasm",
        "Otorhinolaryngological Neoplasms",
        "Neoplasms, Otorhinolaryngologic",
        "Otorhinolaryngeal Cancer",
        "Cancer, Otorhinolaryngeal",
        "Cancers, Otorhinolaryngeal",
        "Otorhinolaryngeal Cancers",
        "Ear Neoplasm",
        "Neoplasm, Ear",
        "Neoplasms, Ear",
        "Neoplasms of Ear Auricle",
        "Ear Auricle Neoplasm",
        "Ear Auricle Neoplasms",
        "Neoplasms, Auricular",
        "Auricular Neoplasms",
        "Cancer of Ear",
        "Ear Cancer",
        "Cancer of the Ear",
        "Cancer of Ear Auricle",
        "Ear Auricle Cancer",
        "Ear Auricle Cancers",
        "Auricular Cancer",
        "Auricular Cancers",
        "Cancer, Auricular",
        "Cancers, Auricular",
        "Neoplasms, Laryngeal",
        "Laryngeal Neoplasm",
        "Neoplasm, Laryngeal",
        "Larynx Neoplasms",
        "Larynx Neoplasm",
        "Neoplasm, Larynx",
        "Neoplasms, Larynx",
        "Cancer of Larynx",
        "Larynx Cancers",
        "Laryngeal Cancer",
        "Cancer, Laryngeal",
        "Cancers, Laryngeal",
        "Laryngeal Cancers",
        "Larynx Cancer",
        "Cancer, Larynx",
        "Cancers, Larynx",
        "Cancer of the Larynx",
        "Neoplasm, Nose",
        "Nose Neoplasm",
        "Neoplasms, Nose",
        "Nasal Neoplasms",
        "Nasal Neoplasm",
        "Neoplasm, Nasal",
        "Neoplasms, Nasal",
        "Cancer of Nose",
        "Nose Cancers",
        "Nose Cancer",
        "Cancer, Nose",
        "Cancers, Nose",
        "Nasal Cancer",
        "Cancer, Nasal",
        "Cancers, Nasal",
        "Nasal Cancers",
        "Cancer of the Nose",
        "Neoplasm, Pharyngeal",
        "Pharyngeal Neoplasm",
        "Neoplasms, Pharynx",
        "Neoplasms, Pharyngeal",
        "Pharynx Neoplasms",
        "Neoplasm, Pharynx",
        "Pharynx Neoplasm",
        "Cancer of Pharynx",
        "Pharynx Cancer",
        "Pharynx Cancers",
        "Cancer of the Pharynx",
        "Pharnyx Cancer",
        "Cancer, Pharnyx",
        "Cancers, Pharnyx",
        "Pharnyx Cancers",
        "Pharyngeal Cancer",
        "Cancer, Pharyngeal",
        "Cancers, Pharyngeal",
        "Pharyngeal Cancers",
        "Hypopharyngeal Neoplasms",
        "Nasopharyngeal Neoplasms",
        "Nasopharyngeal Carcinoma",
        "Oropharyngeal Neoplasms",
        "Tonsillar Neoplasms",
        "Head And Neck Squamous Cell Carcinomas",
        "Squamous Cell Carcinoma, Head And Neck",
        "Squamous Cell Carcinoma of the Head and Neck",
        "Head and Neck Squamous Cell Carcinoma",
        "HNSCC",
        "Carcinoma, Squamous Cell of Head and Neck",
        "Squamous Cell Carcinoma of the Larynx",
        "Laryngeal Squamous Cell Carcinoma",
        "Squamous Cell Carcinoma of Larynx",
        "Squamous Cell Carcinoma of the Nasal Cavity",
        "Oral Tongue Squamous Cell Carcinoma",
        "Hypopharyngeal Squamous Cell Carcinoma",
        "Oral Squamous Cell Carcinoma",
        "Oral Cavity Squamous Cell Carcinoma",
        "Oral Squamous Cell Carcinomas",
        "Squamous Cell Carcinoma of the Mouth",
        "Oropharyngeal Squamous Cell Carcinoma"
        # Salivary Gland Cancer
        "Gland Neoplasm, Salivary",
        "Gland Neoplasms, Salivary",
        "Neoplasm, Salivary Gland",
        "Salivary Gland Neoplasm",
        "Neoplasms, Salivary Gland",
        "Salivary Gland Lymphadenomas",
        "Lymphadenoma, Salivary Gland",
        "Lymphadenomas, Salivary Gland",
        "Salivary Gland Lymphadenoma",
        "Non-Sebaceous Lymphadenomas",
        "Lymphadenoma, Non-Sebaceous",
        "Lymphadenomas, Non-Sebaceous",
        "Non Sebaceous Lymphadenomas",
        "Non-Sebaceous Lymphadenoma",
        "Cancer of Salivary Gland",
        "Salivary Gland Cancers",
        "Cancer of the Salivary Gland",
        "Salivary Gland Cancer",
        "Cancer, Salivary Gland",
        "Cancers, Salivary Gland",
        "Sebaceous Lymphadenomas",
        "Lymphadenoma, Sebaceous",
        "Lymphadenomas, Sebaceous",
        "Sebaceous Lymphadenoma",
        "Neoplasm, Parotid",
        "Parotid Neoplasm",
        "Neoplasms, Parotid",
        "Cancer of Parotid",
        "Parotid Cancers",
        "Parotid Cancer",
        "Cancer, Parotid",
        "Cancers, Parotid",
        "Cancer of the Parotid",
        "Gland Neoplasm, Salivary",
        "Gland Neoplasms, Salivary",
        "Neoplasm, Salivary Gland",
        "Salivary Gland Neoplasm",
        "Neoplasms, Salivary Gland",
        "Salivary Gland Lymphadenomas",
        "Lymphadenoma, Salivary Gland",
        "Lymphadenomas, Salivary Gland",
        "Salivary Gland Lymphadenoma",
        "Non-Sebaceous Lymphadenomas",
        "Lymphadenoma, Non-Sebaceous",
        "Lymphadenomas, Non-Sebaceous",
        "Non Sebaceous Lymphadenomas",
        "Non-Sebaceous Lymphadenoma",
        "Cancer of Salivary Gland",
        "Salivary Gland Cancers",
        "Cancer of the Salivary Gland",
        "Salivary Gland Cancer",
        "Cancer, Salivary Gland",
        "Cancers, Salivary Gland",
        "Sebaceous Lymphadenomas",
        "Lymphadenoma, Sebaceous",
        "Lymphadenomas, Sebaceous",
        "Sebaceous Lymphadenoma",
        "Gland Neoplasm, Sublingual",
        "Gland Neoplasms, Sublingual",
        "Neoplasm, Sublingual Gland",
        "Neoplasms, Sublingual Gland",
        "Sublingual Gland Neoplasm",
        "Gland Neoplasm, Submandibular",
        "Gland Neoplasms, Submandibular",
        "Neoplasm, Submandibular Gland",
        "Neoplasms, Submandibular Gland",
        "Submandibular Gland Neoplasm"
        # Central Nervous System Germ Cell Tumors
        "Neoplasms, Germ Cell and Embryonic",
        "Germ Cell and Embryonic Neoplasms",
        "Germ Cell and Embryonal Neoplasms",
        "Cancer, Embryonal and Mixed",
        "Neoplasms, Germ Cell",
        "Germ Cell Tumor",
        "Germ Cell Tumors",
        "Tumor, Germ Cell",
        "Tumors, Germ Cell",
        "Germ Cell Neoplasms",
        "Neoplasms, Embryonal",
        "Embryonal Neoplasm",
        "Neoplasm, Embryonal",
        "Embryonal Neoplasms",
        "Neoplasms, Embryonal and Mixed",
        "Cancer, Embryonal",
        "Cancers, Embryonal",
        "Embryonal Cancer",
        "Embryonal Cancers",
        "Germ Cell Cancer",
        "Cancer, Germ Cell",
        "Cancers, Germ Cell",
        "Germ Cell Cancers",
        "Carcinomas, Embryonal",
        "Embryonal Carcinoma",
        "Embryonal Carcinomas",
        "Chordomas",
        "Germinomas",
        "Dysgerminomas",
        "Disgerminoma",
        "Disgerminomas",
        "Seminomas",
        "Gonadoblastomas",
        "Mesonephromas",
        "Endodermal Sinus Tumors",
        "Tumor, Endodermal Sinus",
        "Tumors, Endodermal Sinus",
        "Yolk Sac Tumor",
        "Tumor, Yolk Sac",
        "Tumors, Yolk Sac",
        "Yolk Sac Tumors",
        "Neuroectodermal Tumor",
        "Tumor, Neuroectodermal",
        "Tumors, Neuroectodermal",
        "Craniopharyngiomas",
        "Neoplasm, Rathke's Cleft",
        "Neoplasm, Rathke's Cleft",
        "Rathke's Pouch Tumor",
        "Rathke's Pouch Tumor",
        "Tumor, Rathke's Pouch",
        "Rathke's Pouch Tumor",
        "Tumor, Rathke's Pouch",
        "Rathke's Cleft Neoplasm",
        "Rathke's Cleft Neoplasm",
        "Neoplasm, Rathke's Cleft",
        "Rathke's Cleft Neoplasm",
        "Craniopharyngioma, Papillary",
        "Craniopharyngiomas, Papillary",
        "Papillary Craniopharyngioma",
        "Papillary Craniopharyngiomas",
        "Craniopharyngioma, Child",
        "Child Craniopharyngioma",
        "Child Craniopharyngiomas",
        "Craniopharyngiomas, Child",
        "Craniopharyngioma, Adamantinous",
        "Adamantinous Craniopharyngioma",
        "Adamantinous Craniopharyngiomas",
        "Craniopharyngiomas, Adamantinous",
        "Craniopharyngioma, Adult",
        "Adult Craniopharyngioma",
        "Adult Craniopharyngiomas",
        "Craniopharyngiomas, Adult",
        "Neuroepithelial Tumors",
        "Neuroepithelial Tumor",
        "Tumor, Neuroepithelial",
        "Tumors, Neuroepithelial",
        "Neuroepithelial Neoplasms",
        "Neoplasm, Neuroepithelial",
        "Neuroepithelial Neoplasm",
        "Spongioblastoma, Polar",
        "Polar Spongioblastoma",
        "Polar Spongioblastomas",
        "Spongioblastomas, Polar",
        "Gliomatosis Cerebri",
        "Astroblastoma",
        "Astroblastomas",
        "Ependymoastrocytoma",
        "Ependymoastrocytomas",
        "Melanotic Neuroectodermal Tumor",
        "Melanotic Neuroectodermal Tumors",
        "Neuroectodermal Tumors, Melanotic",
        "Tumor, Melanotic Neuroectodermal",
        "Tumors, Melanotic Neuroectodermal",
        "Retinal Anlage Tumor",
        "Anlage Tumor, Retinal",
        "Anlage Tumors, Retinal",
        "Retinal Anlage Tumors",
        "Tumor, Retinal Anlage",
        "Tumors, Retinal Anlage",
        "Melanoameloblastoma",
        "Melanoameloblastomas",
        "Progonoma, Melanotic",
        "Melanotic Progonoma",
        "Melanotic Progonomas",
        "Progonomas, Melanotic",
        "Neuroendocrine Tumor",
        "Tumor, Neuroendocrine",
        "Tumors, Neuroendocrine",
        "Teratocarcinomas",
        "Teratomas",
        "Dysembryoma",
        "Dysembryomas",
        "Teratoid Tumor",
        "Teratoid Tumors",
        "Tumor, Teratoid",
        "Tumors, Teratoid",
        "Teratoma, Benign",
        "Benign Teratoma",
        "Benign Teratomas",
        "Teratomas, Benign",
        "Teratoma, Mature",
        "Teratoma, Cystic",
        "Teratoma, Malignant",
        "Malignant Teratoma",
        "Malignant Teratomas",
        "Teratomas, Malignant",
        "Teratoma, Immature",
        "Immature Teratoma",
        "Immature Teratomas",
        "Teratomas, Immature",
        "Dermoid Cyst",
        "Struma Ovarii",
        "Neoplasms, Trophoblastic",
        "Neoplasm, Trophoblastic",
        "Trophoblastic Neoplasm",
        "Trophoblastic Tumor",
        "Trophoblastic Tumors",
        "Tumor, Trophoblastic",
        "Tumors, Trophoblastic",
        "Trophoblast Neoplasms",
        "Neoplasm, Trophoblast",
        "Neoplasms, Trophoblast",
        "Trophoblast Neoplasm",
        "Trophoblast Tumor",
        "Trophoblast Tumors",
        "Tumor, Trophoblast",
        "Tumors, Trophoblast",
        "Trophoblastic Cancer",
        "Cancer, Trophoblastic",
        "Cancers, Trophoblastic",
        "Trophoblastic Cancers",
        "Trophoblast Cancer",
        "Cancer, Trophoblast",
        "Cancers, Trophoblast",
        "Trophoblast Cancers",
        "Choriocarcinomas",
        "Adenoma, Acidophil",
        "Adenoma, Basophil",
        "Adenoma, Chromophobe",
        "Apudoma",
        "Carcinoid Tumor",
        "Malignant Carcinoid Syndrome +",
        "Carcinoma, Neuroendocrine",
        "Carcinoma, Medullary",
        "Carcinoma, Merkel Cell",
        "Somatostatinoma",
        "Vipoma",
        "Melanoma",
        "Hutchinson's Melanotic Freckle",
        "Melanoma, Amelanotic",
        "Melanoma, Experimental",
        "Neurilemmoma",
        "Neuroma, Acoustic +",
        "Paraganglioma",
        "Paraganglioma, Extra-Adrenal +",
        "Hyatidiform Mole",
        "Pheochromocytoma"
        # Kaposi Sarcoma
        "Kaposi's Sarcoma",
        "Kaposis Sarcoma",
        "Sarcoma, Kaposi's",
        "Multiple Idiopathic Pigmented Hemangiosarcoma",
        "Kaposi Sarcoma",
        "Neoplasms, Germ Cell and Embryonal",
        "Trophoblastic Neoplasms",
        "Choriocarcinoma",
        "Choriocarcinoma, Non-gestational",
        "Trophoblastic Tumor, Placental Site",
        "Gestational Trophoblastic Disease",
        "Hydatidiform Mole +"
        # Breast Cancer
        "Breast Neoplasm",
        "Neoplasm, Breast",
        "Breast Tumors",
        "Breast Tumor",
        "Tumor, Breast",
        "Tumors, Breast",
        "Neoplasms, Breast",
        "Breast Cancer",
        "Cancer, Breast",
        "Mammary Cancer",
        "Cancer, Mammary",
        "Mammary Cancers",
        "Malignant Neoplasm of Breast",
        "Breast Malignant Neoplasm",
        "Malignant Tumor of Breast",
        "Breast Malignant Tumor",
        "Cancer of Breast",
        "Cancer of the Breast",
        "Mammary Carcinoma, Human",
        "Carcinoma, Human Mammary",
        "Carcinomas, Human Mammary",
        "Human Mammary Carcinomas",
        "Mammary Carcinomas, Human",
        "Human Mammary Carcinoma",
        "Mammary Neoplasms, Human",
        "Human Mammary Neoplasm",
        "Neoplasm, Human Mammary",
        "Neoplasms, Human Mammary",
        "Mammary Neoplasm, Human",
        "Breast Carcinoma",
        "Carcinoma, Breast",
        "Breast Carcinoma In Situ",
        "Carcinoma, Intraductal, Noninfiltrating",
        "Paget's Disease, Mammary",
        "Breast Neoplasms, Male",
        "Carcinoma, Ductal, Breast",
        "Carcinoma, Lobular",
        "Hereditary Breast and Ovarian Cancer Syndrome",
        "Inflammatory Breast Neoplasms",
        "Triple Negative Breast Neoplasms",
        "Unilateral Breast Neoplasms",
        # endocrine gland neoplasms
        "Endocrine Gland Neoplasm",
        "Neoplasm, Endocrine Gland",
        "Neoplasms, Endocrine Gland",
        "Carcinoma of Endocrine Gland",
        "Endocrine Gland Carcinoma",
        "Carcinoma, Endocrine Gland",
        "Endocrine Cancer",
        "Cancer, Endocrine",
        "Cancers, Endocrine",
        "Endocrine Cancers",
        "Endocrine Gland Cancer",
        "Cancer, Endocrine Gland",
        "Cancer of Endocrine Gland",
        "Cancer of the Endocrine Gland",
        "Adrenal Gland Neoplasms",
        "Multiple Endocrine Neoplasia",
        "Carcinoma, Ovarian Epithelial",
        "Granulosa Cell Tumor",
        "Hereditary Breast and Ovarian Cancer Syndrome",
        "Luteoma",
        "Meigs Syndrome",
        "Sertoli-Leydig Cell Tumor",
        "Thecoma",
        "Adenoma, Islet Cell",
        "Carcinoma, Islet Cell",
        "Carcinoma, Pancreatic Ductal",
        "Pancreatic Intraductal Neoplasms",
        "Paraneoplastic Endocrine Syndromes",
        "Parathyroid Neoplasms",
        "ACTH-Secreting Pituitary Adenoma",
        "Growth Hormone-Secreting Pituitary Adenoma",
        "Prolactinoma",
        "Sertoli-Leydig Cell Tumor",
        "Thyroid Cancer, Papillary"
        # carcinoma, neuroendocrine
        "Carcinomas, Neuroendocrine",
        "Neuroendocrine Carcinoma",
        "Neuroendocrine Carcinomas",
        "Carcinoma, Medullary",
        "Carcinoma, Merkel Cell",
        "Somatostatinoma",
        "Vipoma",
        # Adrenocortical Carcinoma
        "Adrenocortical Carcinomas",
        "Carcinomas, Adrenocortical",
        "Carcinoma, Adrenocortical",
        "Carcinoma, Adrenal Cortical",
        "Adrenal Cortical Carcinoma",
        "Adrenal Cortical Carcinomas",
        "Carcinomas, Adrenal Cortical",
        # Neuroendocrine Carcinoma of the Skin (Merkel Cell Carcinoma)
        "Merkle Tumors",
        "Tumors, Merkle",
        "Merkel Cell Tumor",
        "Tumor, Merkel Cell",
        "Merkel Cell Cancer",
        "Cancer, Merkel Cell",
        "Cell Cancer, Merkel",
        "Merkel Cell Carcinoma",
        # Parathyroid Cancer
        "Neoplasm, Parathyroid",
        "Parathyroid Neoplasm",
        "Neoplasms, Parathyroid",
        "Parathyroid Adenoma",
        "Adenoma, Parathyroid",
        "Adenomas, Parathyroid",
        "Parathyroid Adenomas",
        "Parathyroid Carcinoma",
        "Carcinoma, Parathyroid",
        "Carcinomas, Parathyroid",
        "Parathyroid Carcinomas",
        "Cancer of Parathyroid",
        "Parathyroid Cancers",
        "Cancer of the Parathyroid",
        "Parathyroid Cancer",
        "Cancer, Parathyroid",
        "Cancers, Parathyroid"
        # Paraganglioma
        "Paragangliomas",
        "Paraganglioma, Gangliocytic",
        "Gangliocytic Paraganglioma",
        "Gangliocytic Paragangliomas",
        "Paragangliomata",
        "Paragangliomatas",
        "Carotid Body Tumor",
        "Glomus Jugulare Tumor",
        "Glomus Tympanicum Tumor",
        "Pheochromocytoma",
        # Pheochromocytoma
        "Pheochromocytomas",
        "Pheochromocytoma, Extra-Adrenal",
        "Extra-Adrenal Pheochromocytoma",
        "Extra-Adrenal Pheochromocytomas",
        "Pheochromocytoma, Extra Adrenal",
        "Pheochromocytomas, Extra-Adrenal",
        # Pituitary Tumor
        "Neoplasm, Pituitary",
        "Neoplasms, Pituitary",
        "Pituitary Neoplasm",
        "Pituitary Tumors",
        "Pituitary Tumor",
        "Tumor, Pituitary",
        "Tumors, Pituitary",
        "Pituitary Adenoma",
        "Adenoma, Pituitary",
        "Adenomas, Pituitary",
        "Pituitary Adenomas",
        "Pituitary Carcinoma",
        "Carcinoma, Pituitary",
        "Carcinomas, Pituitary",
        "Pituitary Carcinomas",
        "Cancer of the Pituitary",
        "Pituitary Cancer",
        "Cancer, Pituitary",
        "Cancers, Pituitary",
        "Cancer of Pituitary",
        "Pituitary Cancers",
        "ACTH-Secreting Pituitary Adenoma",
        "Nelson Syndrome",
        "Growth Hormone-Secreting Pituitary Adenoma",
        "Prolactinoma"
        # Thyroid Cancer
        "Neoplasm, Thyroid",
        "Thyroid Neoplasm",
        "Neoplasms, Thyroid",
        "Thyroid Carcinoma",
        "Carcinoma, Thyroid",
        "Carcinomas, Thyroid",
        "Thyroid Carcinomas",
        "Cancer of Thyroid",
        "Thyroid Cancers",
        "Thyroid Cancer",
        "Cancer, Thyroid",
        "Cancers, Thyroid",
        "Cancer of the Thyroid",
        "Thyroid Adenoma",
        "Adenoma, Thyroid",
        "Adenomas, Thyroid",
        "Thyroid Adenomas",
        "Thyroid Cancer" "Cancer, Papillary Thyroid",
        "Cancers, Papillary Thyroid",
        "Papillary Thyroid Cancer",
        "Papillary Thyroid Cancers",
        "Thyroid Cancers, Papillary",
        "Thyroid Carcinoma, Papillary",
        "Carcinoma, Papillary Thyroid",
        "Carcinomas, Papillary Thyroid",
        "Papillary Thyroid Carcinomas",
        "Thyroid Carcinomas, Papillary",
        "Papillary Carcinoma Of Thyroid",
        "Papillary Thyroid Carcinoma",
        "Familial Nonmedullary Thyroid Cancer",
        "Nonmedullary Thyroid Carcinoma",
        "Carcinoma, Nonmedullary Thyroid",
        "Carcinomas, Nonmedullary Thyroid",
        "Nonmedullary Thyroid Carcinomas",
        "Thyroid Carcinoma, Nonmedullary",
        "Thyroid Carcinomas, Nonmedullary"
        # Retinoblastoma
        "Retinoblastomas",
        "Neuroblastoma, Retinal",
        "Neuroblastomas, Retinal",
        "Retinal Neuroblastoma",
        "Retinal Neuroblastomas",
        "Glioma, Retinal",
        "Gliomas, Retinal",
        "Retinal Glioma",
        "Retinal Gliomas",
        "Eye Cancer, Retinoblastoma",
        "Cancer, Retinoblastoma Eye",
        "Cancers, Retinoblastoma Eye",
        "Eye Cancers, Retinoblastoma",
        "Retinoblastoma Eye Cancer",
        "Retinoblastoma Eye Cancers",
        "Glioblastoma, Retinal",
        "Glioblastomas, Retinal",
        "Retinal Glioblastoma",
        "Retinal Glioblastomas",
        "Sporadic Retinoblastoma",
        "Retinoblastoma, Sporadic",
        "Retinoblastomas, Sporadic",
        "Sporadic Retinoblastomas",
        "Familial Retinoblastoma",
        "Familial Retinoblastomas",
        "Retinoblastoma, Familial",
        "Retinoblastomas, Familial",
        "Hereditary Retinoblastoma",
        "Hereditary Retinoblastomas",
        "Retinoblastoma, Hereditary",
        "Retinoblastomas, Hereditary"
        # Bladder Cancer
        "Neoplasm, Urinary Bladder",
        "Urinary Bladder Neoplasm",
        "Bladder Tumors",
        "Bladder Tumor",
        "Tumor, Bladder",
        "Tumors, Bladder",
        "Neoplasms, Bladder",
        "Bladder Neoplasms",
        "Bladder Neoplasm",
        "Neoplasm, Bladder",
        "Urinary Bladder Cancer",
        "Cancer, Urinary Bladder",
        "Malignant Tumor of Urinary Bladder",
        "Cancer of the Bladder",
        "Bladder Cancer",
        "Bladder Cancers",
        "Cancer, Bladder",
        "Cancer of Bladder"
        # Kidney (Renal Cell) Cancer
        "Carcinomas, Renal Cell",
        "Renal Cell Carcinomas",
        "Nephroid Carcinoma",
        "Carcinoma, Nephroid",
        "Nephroid Carcinomas",
        "Adenocarcinoma Of Kidney",
        "Adenocarcinoma Of Kidneys",
        "Kidney, Adenocarcinoma Of",
        "Renal Cell Carcinoma",
        "Renal Cell Cancer",
        "Cancer, Renal Cell",
        "Renal Cell Cancers",
        "Adenocarcinoma, Renal",
        "Renal Adenocarcinoma",
        "Renal Adenocarcinomas",
        "Renal Carcinoma",
        "Carcinoma, Renal",
        "Renal Carcinomas",
        "Adenocarcinoma, Renal Cell",
        "Adenocarcinomas, Renal Cell",
        "Renal Cell Adenocarcinoma",
        "Renal Cell Adenocarcinomas",
        "Chromophobe Renal Cell Carcinoma",
        "Sarcomatoid Renal Cell Carcinoma",
        "Papillary Renal Cell Carcinoma",
        "Renal Cell Carcinoma, Papillary",
        "Chromophil Renal Cell Carcinoma",
        "Clear Cell Renal Cell Carcinoma",
        "Grawitz Tumor",
        "Tumor, Grawitz",
        "Clear Cell Renal Carcinoma",
        "Carcinoma, Hypernephroid",
        "Hypernephroid Carcinoma",
        "Hypernephroid Carcinomas",
        "Hypernephroma",
        "Hypernephromas",
        "Collecting Duct Carcinoma (Kidney)",
        "Carcinoma, Collecting Duct (Kidney)",
        "Carcinomas, Collecting Duct (Kidney)",
        "Collecting Duct Carcinomas (Kidney)",
        "Collecting Duct Carcinoma of the Kidney",
        "Renal Collecting Duct Carcinoma",
        "Collecting Duct Carcinoma",
        "Carcinoma, Collecting Duct",
        "Carcinomas, Collecting Duct",
        "Collecting Duct Carcinomas"
        # Penile Cancer
        "Penis Neoplasms",
        "Neoplasm, Penis",
        "Penis Neoplasm",
        "Neoplasms, Penis",
        "Neoplasms, Penile",
        "Neoplasm, Penile",
        "Penile Neoplasm",
        "Cancer of Penis",
        "Penis Cancers",
        "Cancer of the Penis",
        "Penis Cancer",
        "Cancer, Penis",
        "Cancers, Penis",
        "Penile Cancer",
        "Cancer, Penile",
        "Cancers, Penile",
        "Penile Cancers"
        # Prostate Cancer
        "Prostate Neoplasms",
        "Neoplasms, Prostate",
        "Neoplasm, Prostate",
        "Prostate Neoplasm",
        "Neoplasms, Prostatic",
        "Neoplasm, Prostatic",
        "Prostatic Neoplasm",
        "Prostate Cancer",
        "Cancer, Prostate",
        "Cancers, Prostate",
        "Prostate Cancers",
        "Cancer of the Prostate",
        "Prostatic Cancer",
        "Cancer, Prostatic",
        "Cancers, Prostatic",
        "Prostatic Cancers",
        "Cancer of Prostate"
        # Renal Pelvis and Ureter Cancer, Transitional Cell
        "Carcinomas, Transitional Cell",
        "Cell Carcinoma, Transitional",
        "Cell Carcinomas, Transitional",
        "Transitional Cell Carcinoma",
        "Transitional Cell Carcinomas",
        # Testicular Cancer
        "Testicular Neoplasm",
        "Neoplasm, Testicular",
        "Testicular Tumors",
        "Neoplasms, Testis",
        "Neoplasm, Testis",
        "Testis Neoplasm",
        "Testis Neoplasms",
        "Testicular Tumor",
        "Tumor, Testicular",
        "Tumors, Testicular",
        "Neoplasms, Testicular",
        "Cancer of Testis",
        "Testis Cancer",
        "Cancer, Testis",
        "Cancers, Testis",
        "Testis Cancers",
        "Cancer of the Testes",
        "Cancer of the Testis",
        "Testicular Cancer",
        "Cancer, Testicular",
        "Cancers, Testicular",
        "Testicular Cancers",
        "Tumor of Rete Testis",
        "Rete Testis Tumor",
        "Rete Testis Tumors",
        "Testis Tumor, Rete",
        "Testis Tumors, Rete" "Sertoli-Leydig Cell Tumor",
        "Leydig Cell Tumor",
        "Sertoli Cell Tumor",
        # Urethral Cancer
        "Urethra Neoplasms",
        "Neoplasm, Urethra",
        "Neoplasms, Urethra",
        "Urethra Neoplasm",
        "Neoplasms, Urethral",
        "Neoplasm, Urethral",
        "Urethral Neoplasm",
        "Cancer of Urethra",
        "Urethra Cancers",
        "Urethra Cancer",
        "Cancer, Urethra",
        "Cancers, Urethra",
        "Urethral Cancer",
        "Cancer, Urethral",
        "Cancers, Urethral",
        "Urethral Cancers",
        "Cancer of the Urethra"
        # Cervical Cancer
        "Cervical Neoplasm, Uterine",
        "Neoplasm, Uterine Cervical",
        "Uterine Cervical Neoplasm",
        "Neoplasms, Cervical",
        "Cervical Neoplasms",
        "Cervical Neoplasm",
        "Neoplasms, Cervix",
        "Cervix Neoplasm",
        "Neoplasm, Cervix",
        "Cervix Neoplasms",
        "Cancer of the Uterine Cervix",
        "Cancer of the Cervix",
        "Cervical Cancer",
        "Cancer, Cervical",
        "Cervical Cancers",
        "Uterine Cervical Cancer",
        "Cancer, Uterine Cervical",
        "Cervical Cancer, Uterine",
        "Uterine Cervical Cancers",
        "Cancer of Cervix",
        "Cervix Cancer",
        "Cancer, Cervix"
        # Endometrial Cancer
        "Endometrial Neoplasm",
        "Neoplasm, Endometrial",
        "Neoplasms, Endometrial",
        "Endometrial Carcinoma",
        "Carcinoma, Endometrial",
        "Carcinomas, Endometrial",
        "Endometrial Carcinomas",
        "Endometrial Cancer",
        "Cancer, Endometrial",
        "Cancers, Endometrial",
        "Endometrial Cancers",
        "Endometrium Cancer",
        "Cancer, Endometrium",
        "Cancers, Endometrium",
        "Cancer of the Endometrium",
        "Carcinoma of Endometrium",
        "Endometrium Carcinoma",
        "Endometrium Carcinomas",
        "Cancer of Endometrium",
        "Endometrium Cancers" "Endometrial Stromal Tumors",
        "Sarcoma, Endometrial Stromal",
        "Carcinoma, Endometrioid",
        # Fallopian Tube Cancer
        "Fallopian Tube Neoplasm",
        "Neoplasm, Fallopian Tube",
        "Neoplasms, Fallopian Tube",
        "Fallopian Tube Cancer",
        "Cancer, Fallopian Tube",
        "Cancers, Fallopian Tube",
        "Fallopian Tube Cancers",
        "Cancer of the Fallopian Tube",
        # leukemia
        "Leukemias",
        "Leucocythaemia",
        "Leucocythaemias",
        "Leucocythemia",
        "Leucocythemias" "Enzootic Bovine Leukosis",
        "Leukemia, Experimental",
        "Avian Leukosis",
        "Leukemia L1210",
        "Leukemia L5178",
        "Leukemia P388",
        "Leukemia, Feline",
        "Leukemia, Hairy Cell",
        "Leukemia, Lymphoid",
        "Leukemia, B-Cell +",
        "Leukemia, Biphenotypic, Acute",
        "Leukemia, Prolymphocytic +",
        "Leukemia, T-Cell +",
        "Precursor Cell Lymphoblastic Leukemia-Lymphoma +",
        "Leukemia, Mast-Cell",
        "Leukemia, Myeloid",
        "Leukemia, Myelogenous, Chronic, BCR-ABL Positive +",
        "Leukemia, Myeloid, Acute +",
        "Leukemia, Myeloid, Chronic, Atypical, BCR-ABL Negative",
        "Leukemia, Myelomonocytic, Acute",
        "Leukemia, Myelomonocytic, Chronic",
        "Leukemia, Myelomonocytic, Juvenile",
        "Sarcoma, Myeloid",
        "Leukemia, Plasma Cell",
        "Leukemia, Radiation-Induced"
        # Acute Lymphoblastic Leukemia
        "Precursor Cell Lymphoblastic Leukemia Lymphoma",
        "Leukemia, Acute Lymphoblastic",
        "Acute Lymphoblastic Leukemia",
        "Leukemia, Lymphoblastic",
        "Leukemia, Lymphoblastic, Acute",
        "Leukemia, Lymphocytic, Acute",
        "Lymphoblastic Leukemia",
        "Lymphoblastic Leukemia, Acute",
        "Lymphoblastic Lymphoma",
        "Lymphocytic Leukemia, Acute",
        "Acute Lymphocytic Leukemia",
        "Leukemia, Acute Lymphocytic",
        "Lymphoma, Lymphoblastic",
        "Acute Lymphoid Leukemia",
        "Leukemia, Acute Lymphoid",
        "Lymphoid Leukemia, Acute",
        "Leukemia, Lymphoid, Acute",
        "Leukemia, Lymphocytic, Acute, L1",
        "Lymphocytic Leukemia, L1",
        "L1 Lymphocytic Leukemia",
        "Leukemia, L1 Lymphocytic",
        "Lymphoblastic Leukemia, Acute, Childhood",
        "Lymphoblastic Leukemia, Acute, L1",
        "ALL, Childhood",
        "Childhood ALL",
        "Leukemia, Lymphoblastic, Acute, L1",
        "Leukemia, Lymphocytic, Acute, L2",
        "Lymphocytic Leukemia, L2",
        "L2 Lymphocytic Leukemia",
        "Leukemia, L2 Lymphocytic",
        "Lymphoblastic Leukemia, Acute, Adult",
        "Lymphoblastic Leukemia, Acute, L2",
        "Leukemia, Lymphoblastic, Acute, L2",
        "Leukemia, Lymphoblastic, Acute, Philadelphia-Positive"
        # Acute Myeloid Leukemia, Adult
        "Acute Myeloid Leukemia",
        "Acute Myeloid Leukemias",
        "Leukemias, Acute Myeloid",
        "Myeloid Leukemias, Acute",
        "ANLL",
        "Leukemia, Acute Myelogenous",
        "Leukemia, Acute Myeloid",
        "Leukemia, Myeloblastic, Acute",
        "Leukemia, Myelocytic, Acute",
        "Leukemia, Myelogenous, Acute",
        "Leukemia, Nonlymphoblastic, Acute",
        "Leukemia, Nonlymphocytic, Acute",
        "Myeloblastic Leukemia, Acute",
        "Acute Myeloblastic Leukemia",
        "Acute Myeloblastic Leukemias",
        "Leukemia, Acute Myeloblastic",
        "Leukemias, Acute Myeloblastic",
        "Myeloblastic Leukemias, Acute",
        "Myelocytic Leukemia, Acute",
        "Acute Myelocytic Leukemia",
        "Acute Myelocytic Leukemias",
        "Leukemia, Acute Myelocytic",
        "Leukemias, Acute Myelocytic",
        "Myelocytic Leukemias, Acute",
        "Myelogenous Leukemia, Acute",
        "Myeloid Leukemia, Acute",
        "Nonlymphoblastic Leukemia, Acute",
        "Acute Nonlymphoblastic Leukemia",
        "Acute Nonlymphoblastic Leukemias",
        "Leukemia, Acute Nonlymphoblastic",
        "Leukemias, Acute Nonlymphoblastic",
        "Nonlymphoblastic Leukemias, Acute",
        "Nonlymphocytic Leukemia, Acute",
        "Acute Nonlymphocytic Leukemia",
        "Acute Nonlymphocytic Leukemias",
        "Leukemia, Acute Nonlymphocytic",
        "Leukemias, Acute Nonlymphocytic",
        "Nonlymphocytic Leukemias, Acute",
        "Acute Myelogenous Leukemia",
        "Acute Myelogenous Leukemias",
        "Leukemias, Acute Myelogenous",
        "Myelogenous Leukemias, Acute",
        "Myeloid Leukemia, Acute, M1",
        "Leukemia, Myeloid, Acute, M1",
        "Acute Myeloid Leukemia without Maturation",
        "Leukemia, Myeloid, Acute, M2",
        "Myeloid Leukemia, Acute, M2",
        "Acute Myeloid Leukemia with Maturation"
        # Chronic Lymphocytic Leukemia
        "Lymphoma, Lymphoplasmacytoid, CLL",
        "Lymphoma, Small-Cell",
        "Lymphoma, Small Cell",
        "Lymphomas, Small-Cell",
        "Small-Cell Lymphomas",
        "Lymphoplasmacytoid Lymphoma, CLL",
        "CLL Lymphoplasmacytoid Lymphoma",
        "CLL Lymphoplasmacytoid Lymphomas",
        "Lymphoma, CLL Lymphoplasmacytoid",
        "Lymphomas, CLL Lymphoplasmacytoid",
        "Lymphoplasmacytoid Lymphomas, CLL",
        "Small-Cell Lymphoma",
        "Small Cell Lymphoma",
        "Lymphoblastic Leukemia, Chronic",
        "Chronic Lymphoblastic Leukemia",
        "Chronic Lymphoblastic Leukemias",
        "Leukemias, Chronic Lymphoblastic",
        "Lymphoblastic Leukemias, Chronic",
        "Lymphocytic Leukemia, Chronic",
        "Chronic Lymphocytic Leukemias",
        "Lymphocytic Leukemias, Chronic",
        "Lymphocytic Leukemia, Chronic, B Cell",
        "Lymphocytic Leukemia, Chronic, B-Cell",
        "Lymphocytic Lymphoma",
        "Lymphocytic Lymphomas",
        "Lymphomas, Lymphocytic",
        "Lymphocytic Lymphoma, Diffuse, Well Differentiated",
        "Lymphocytic Lymphoma, Diffuse, Well-Differentiated",
        "Lymphocytic Lymphoma, Well Differentiated",
        "Lymphocytic Lymphoma, Well-Differentiated",
        "Lymphocytic Lymphomas, Well-Differentiated",
        "Lymphoma, Well-Differentiated Lymphocytic",
        "Lymphomas, Well-Differentiated Lymphocytic",
        "Well-Differentiated Lymphocytic Lymphoma",
        "Well-Differentiated Lymphocytic Lymphomas",
        "Lymphoma, Lymphocytic",
        "Lymphoma, Lymphocytic, Diffuse, Well Differentiated",
        "B-Cell Chronic Lymphocytic Leukemia",
        "B Cell Chronic Lymphocytic Leukemia",
        "B-Cell Leukemia, Chronic",
        "B Cell Leukemia, Chronic",
        "B-Cell Leukemias, Chronic",
        "Chronic B-Cell Leukemia",
        "Chronic B-Cell Leukemias",
        "Leukemia, Chronic B-Cell",
        "Leukemias, Chronic B-Cell",
        "B-Cell Malignancy, Low-Grade",
        "B Cell Malignancy, Low Grade",
        "B-Cell Malignancies, Low-Grade",
        "Low-Grade B-Cell Malignancies",
        "Low-Grade B-Cell Malignancy",
        "Malignancies, Low-Grade B-Cell",
        "Malignancy, Low-Grade B-Cell",
        "B-Lymphocytic Leukemia, Chronic",
        "B Lymphocytic Leukemia, Chronic",
        "B-Lymphocytic Leukemias, Chronic",
        "Chronic B-Lymphocytic Leukemia",
        "Chronic B-Lymphocytic Leukemias",
        "Leukemia, Chronic B-Lymphocytic",
        "Leukemias, Chronic B-Lymphocytic",
        "Chronic Lymphocytic Leukemia",
        "Diffuse Well-Differentiated Lymphocytic Lymphoma",
        "Diffuse Well Differentiated Lymphocytic Lymphoma",
        "Disrupted In B-Cell Malignancy",
        "Disrupted In B Cell Malignancy",
        "Leukemia, B Cell, Chronic",
        "Leukemia, B-Cell, Chronic",
        "Leukemia, Chronic Lymphatic",
        "Chronic Lymphatic Leukemia",
        "Chronic Lymphatic Leukemias",
        "Leukemias, Chronic Lymphatic",
        "Lymphatic Leukemia, Chronic",
        "Lymphatic Leukemias, Chronic",
        "Leukemia, Chronic Lymphocytic",
        "Leukemia, Chronic Lymphocytic, B-Cell",
        "Leukemia, Lymphoblastic, Chronic",
        "Leukemia, Lymphocytic, Chronic",
        "Leukemia, Lymphocytic, Chronic, B Cell",
        "Lymphoma, Lymphocytic, Diffuse, Well-Differentiated",
        "Lymphoma, Lymphocytic, Well Differentiated",
        "Lymphoma, Lymphocytic, Well-Differentiated",
        "Lymphoma, Small Lymphocytic",
        "Lymphocytic Lymphoma, Small",
        "Lymphocytic Lymphomas, Small",
        "Lymphomas, Small Lymphocytic",
        "Small Lymphocytic Lymphoma",
        "Small Lymphocytic Lymphomas",
        "Lymphoma, Small Lymphocytic, Plasmacytoid"
        # Chronic Myelogenous Leukemia
        "Leukemia, Chronic Myeloid",
        "Granulocytic Leukemia, Chronic",
        "Chronic Granulocytic Leukemia",
        "Chronic Granulocytic Leukemias",
        "Granulocytic Leukemias, Chronic",
        "Leukemia, Chronic Granulocytic",
        "Leukemias, Chronic Granulocytic",
        "Leukemia, Granulocytic, Chronic",
        "Myeloid Leukemia, Chronic",
        "Chronic Myeloid Leukemia",
        "Chronic Myeloid Leukemias",
        "Leukemias, Chronic Myeloid",
        "Myeloid Leukemias, Chronic",
        "Leukemia, Myeloid, Chronic",
        "Leukemia, Myelocytic, Chronic",
        "Myelocytic Leukemia, Chronic",
        "Chronic Myelocytic Leukemia",
        "Chronic Myelocytic Leukemias",
        "Leukemia, Chronic Myelocytic",
        "Leukemias, Chronic Myelocytic",
        "Myelocytic Leukemias, Chronic",
        "Leukemia, Myelogenous, Chronic",
        "Myelogenous Leukemia, Chronic",
        "Chronic Myelogenous Leukemia",
        "Chronic Myelogenous Leukemias",
        "Leukemias, Chronic Myelogenous",
        "Myelogenous Leukemias, Chronic",
        "Leukemia, Myeloid, Philadelphia Positive",
        "Myeloid Leukemia, Philadelphia-Positive",
        "Leukemia, Philadelphia-Positive Myeloid",
        "Leukemias, Philadelphia-Positive Myeloid",
        "Myeloid Leukemia, Philadelphia Positive",
        "Myeloid Leukemias, Philadelphia-Positive",
        "Philadelphia-Positive Myeloid Leukemia",
        "Philadelphia-Positive Myeloid Leukemias",
        "Leukemia, Myeloid, Philadelphia-Positive",
        "Leukemia, Myelogenous, Ph1 Positive",
        "Leukemia, Myelogenous, Ph1-Positive",
        "Myelogenous Leukemia, Ph1-Positive",
        "Leukemia, Ph1-Positive Myelogenous",
        "Leukemias, Ph1-Positive Myelogenous",
        "Myelogenous Leukemia, Ph1 Positive",
        "Myelogenous Leukemias, Ph1-Positive",
        "Ph1-Positive Myelogenous Leukemia",
        "Ph1-Positive Myelogenous Leukemias",
        "Leukemia, Myeloid, Ph1 Positive",
        "Leukemia, Myeloid, Ph1-Positive",
        "Myeloid Leukemia, Ph1-Positive",
        "Leukemia, Ph1-Positive Myeloid",
        "Leukemias, Ph1-Positive Myeloid",
        "Myeloid Leukemia, Ph1 Positive",
        "Myeloid Leukemias, Ph1-Positive",
        "Ph1-Positive Myeloid Leukemia",
        "Ph1-Positive Myeloid Leukemias",
        "Leukemia, Chronic Myelogenous"
        # Hodgkin Lymphoma
        "Disease, Hodgkin",
        "Granuloma, Hodgkin's",
        "Hodgkin's Granuloma",
        "Granuloma, Hodgkins",
        "Hodgkins Granuloma",
        "Lymphogranuloma, Malignant",
        "Lymphogranulomas, Malignant",
        "Malignant Lymphogranuloma",
        "Malignant Lymphogranulomas",
        "Hodgkin Lymphoma",
        "Lymphoma, Hodgkin",
        "Hodgkin's Disease",
        "Disease, Hodgkin's",
        "Hodgkin's Lymphoma",
        "Hodgkins Lymphoma",
        "Lymphoma, Hodgkin's",
        "Hodgkins Disease",
        "Disease, Hodgkins",
        "Granuloma, Hodgkin",
        "Hodgkin Granuloma",
        "Granuloma, Malignant",
        "Malignant Granuloma",
        "Malignant Granulomas",
        "Nodular Lymphocyte-Predominant Hodgkin's Lymphoma",
        "Nodular Lymphocyte Predominant Hodgkin's Lymphoma",
        "Nodular Sclerosing Hodgkin's Lymphoma",
        "Lymphocyte-Rich Classical Hodgkin's Lymphoma",
        "Lymphocyte Rich Classical Hodgkin's Lymphoma",
        "Mixed Cellularity Hodgkin's Lymphoma",
        "Hodgkin Lymphoma, Adult",
        "Adult Hodgkin Lymphoma",
        "Lymphocyte Depletion Hodgkin's Lymphoma",
        # Mycosis Fungoides
        "Mycosis Fungoides",
        "Pagetoid Reticulosis",
        # Non-Hodgkin Lymphoma
        "Lymphoma, Non Hodgkin",
        "Lymphoma, Small Cleaved-Cell, Diffuse",
        "Lymphoma, Atypical Diffuse Small Lymphoid",
        "Diffuse Small Cleaved-Cell Lymphoma",
        "Diffuse Small Cleaved Cell Lymphoma",
        "Lymphoma, Small Cleaved Cell, Diffuse",
        "Lymphoma, Nonhodgkins",
        "Nonhodgkins Lymphoma",
        "Lymphoma, Non-Hodgkins",
        "Lymphoma, Non Hodgkins",
        "Non-Hodgkins Lymphoma",
        "Non-Hodgkin's Lymphoma",
        "Non Hodgkin's Lymphoma",
        "Non-Hodgkin Lymphoma",
        "Non Hodgkin Lymphoma",
        "Lymphoma, Nonhodgkin's",
        "Lymphoma, Nonhodgkin",
        "Nonhodgkin's Lymphoma",
        "Small Cleaved-Cell Lymphoma, Diffuse",
        "Small Cleaved Cell Lymphoma, Diffuse",
        "Lymphoma, Non-Hodgkin's",
        "Lymphoma, Non Hodgkin's",
        "Lymphoma, Diffuse",
        "Diffuse Lymphoma",
        "Diffuse Lymphomas",
        "Sarcoma, Lymphatic",
        "Lymphosarcoma",
        "Lymphosarcomas",
        "Lymphatic Sarcoma",
        "Lymphatic Sarcomas",
        "Lymphoma, Low-Grade",
        "Low-Grade Lymphoma",
        "Low-Grade Lymphomas",
        "Lymphoma, Low Grade",
        "Lymphoma, Mixed-Cell",
        "Lymphoma, Mixed Cell",
        "Mixed-Cell Lymphoma",
        "Mixed Cell Lymphoma",
        "Mixed-Cell Lymphomas",
        "Lymphoma, Mixed",
        "Mixed Lymphoma",
        "Mixed Lymphomas",
        "Lymphoma, Mixed Lymphocytic-Histiocytic",
        "Lymphocytic-Histiocytic Lymphoma, Mixed",
        "Lymphocytic-Histiocytic Lymphomas, Mixed",
        "Lymphoma, Mixed Lymphocytic Histiocytic",
        "Mixed Lymphocytic-Histiocytic Lymphoma",
        "Mixed Lymphocytic-Histiocytic Lymphomas",
        "Lymphoma, Non-Hodgkin, Familial",
        "Lymphoma, Small Noncleaved-Cell",
        "Lymphoma, Small Noncleaved Cell",
        "Small Noncleaved-Cell Lymphoma",
        "Noncleaved-Cell Lymphoma, Small",
        "Small Noncleaved Cell Lymphoma",
        "Small Noncleaved-Cell Lymphomas",
        "Diffuse Undifferentiated Lymphoma",
        "Diffuse Undifferentiated Lymphomas",
        "Lymphoma, Diffuse Undifferentiated",
        "Undifferentiated Lymphoma, Diffuse",
        "Lymphoma, Small Non-Cleaved-Cell",
        "Lymphoma, Small Non Cleaved Cell",
        "Non-Cleaved-Cell Lymphoma, Small",
        "Small Non-Cleaved-Cell Lymphomas",
        "Small Non-Cleaved-Cell Lymphoma",
        "Small Non Cleaved Cell Lymphoma",
        "Lymphoma, Undifferentiated, Diffuse",
        "Lymphoma, Intermediate-Grade",
        "Intermediate-Grade Lymphoma",
        "Intermediate-Grade Lymphomas",
        "Lymphoma, Intermediate Grade",
        "Lymphoma, Undifferentiated",
        "Lymphoma, Pleomorphic",
        "Pleomorphic Lymphoma",
        "Pleomorphic Lymphomas",
        "Undifferentiated Lymphoma",
        "Undifferentiated Lymphomas",
        "Reticulum-Cell Sarcoma",
        "Reticulum-Cell Sarcomas",
        "Sarcoma, Reticulum-Cell",
        "Sarcoma, Reticulum Cell",
        "Reticulum Cell Sarcoma",
        "Reticulum Cell Sarcomas",
        "Reticulosarcoma",
        "Reticulosarcomas",
        "Lymphoma, High-Grade",
        "High-Grade Lymphoma",
        "High-Grade Lymphomas",
        "Lymphoma, High Grade",
        "Lymphoma, Mixed-Cell, Diffuse",
        "Mixed Small and Large Cell Lymphoma, Diffuse",
        "Lymphoma, Mixed Small and Large Cell, Diffuse",
        "Lymphoma, Diffuse, Mixed Lymphocytic-Histiocytic",
        "Lymphoma, Small and Large Cleaved-Cell, Diffuse",
        "Lymphoma, Mixed Cell, Diffuse",
        "Mixed-Cell Lymphoma, Diffuse",
        "Mixed Cell Lymphoma, Diffuse",
        "Diffuse Mixed Small and Large Cell Lymphoma",
        "Diffuse Mixed-Cell Lymphoma",
        "Diffuse Mixed Cell Lymphoma",
        "Diffuse Mixed-Cell Lymphomas",
        "Lymphoma, Diffuse Mixed-Cell",
        "Lymphoma, B-Cell",
        "Burkitt Lymphoma",
        "Lymphoma, AIDS-Related",
        "Lymphoma, B-Cell, Marginal Zone",
        "Lymphoma, Large B-Cell, Diffuse +",
        "Lymphoma, Primary Effusion",
        "Lymphomatoid Granulomatosis",
        "Lymphoma, Follicular",
        "Lymphoma, Large-Cell, Immunoblastic",
        "Lymphoma, Mantle-Cell",
        "Lymphoma, T-Cell",
        "Enteropathy-Associated T-Cell Lymphoma",
        "Lymphoma, Extranodal NK-T-Cell",
        "Lymphoma, Large-Cell, Anaplastic",
        "Lymphoma, T-Cell, Cutaneous +",
        "Lymphoma, T-Cell, Peripheral"
        # Sézary Syndrome
        "Syndrome, Sezary",
        "Sezary's Lymphoma",
        "Lymphoma, Sezary's",
        "Sezary Lymphoma",
        "Sezarys Lymphoma",
        "Erythroderma, Sezary",
        "Sezary Erythroderma",
        # Waldenström Macroglobulinemia
        "Macroglobulinemia, Waldenstrom",
        "Lymphoma, Lymphoplasmacytoid",
        "Lymphomas, Lymphoplasmacytoid",
        "Lymphoplasmacytoid Lymphoma",
        "Lymphoplasmacytoid Lymphomas",
        "Macroglobulinemia",
        "Waldenstrom's Macroglobulinemia",
        "Macroglobulinemia, Waldenstrom's",
        "Waldenstroms Macroglobulinemia",
        "Waldenstrom's Macroglobulinaemia",
        "Macroglobulinaemia, Waldenstrom's",
        "Waldenstrom Macroglobulinaemia",
        "Waldenstroms Macroglobulinaemia",
        "Lymphoma, Lymphocytic, Plasmacytoid",
        "Primary Macroglobulinemia",
        "Macroglobulinemia, Primary",
        "Familial Waldenstrom's Macroglobulinaemia",
        "Familial Waldenstrom Macroglobulinaemia",
        "Familial Waldenstroms Macroglobulinaemia",
        "Macroglobulinaemia, Familial Waldenstrom's",
        "Waldenstrom's Macroglobulinaemia, Familial"
        # Langerhans Cell Histiocytosis
        "Histiocytosis, Langerhans Cell",
        "Hand-Schueller-Christian Syndrome",
        "Hand Schueller Christian Syndrome",
        "Syndrome, Hand-Schueller-Christian",
        "Hand-Schüller-Christian Disease",
        "Disease, Hand-Schüller-Christian",
        "Hand Schüller Christian Disease",
        "Hand-Schüller-Christian Syndrome",
        "Hand Schüller Christian Syndrome",
        "Syndrome, Hand-Schüller-Christian",
        "Histiocytosis X",
        "Histiocytosis, Generalized",
        "Generalized Histiocytoses",
        "Generalized Histiocytosis",
        "Histiocytoses, Generalized",
        "Histiocytosis-X",
        "Langerhans Cell Histiocytosis",
        "Cell Histiocytoses, Langerhans",
        "Cell Histiocytosis, Langerhans",
        "Histiocytoses, Langerhans Cell",
        "Langerhans Cell Histiocytoses",
        "Langerhans-Cell Granulomatosis",
        "Granulomatosis, Langerhans-Cell",
        "Langerhans-Cell Histiocytosis",
        "Letterer-Siwe Disease",
        "Disease, Letterer-Siwe",
        "Letterer Siwe Disease",
        "Non-Lipid Reticuloendotheliosis",
        "Non Lipid Reticuloendotheliosis",
        "Non-Lipid Reticuloendothelioses",
        "Reticuloendothelioses, Non-Lipid",
        "Reticuloendotheliosis, Non-Lipid",
        "Schueller-Christian Disease",
        "Disease, Schueller-Christian",
        "Schueller Christian Disease",
        "Systemic Aleukemic Reticuloendotheliosis",
        "Aleukemic Reticuloendothelioses, Systemic",
        "Aleukemic Reticuloendotheliosis, Systemic",
        "Reticuloendothelioses, Systemic Aleukemic",
        "Reticuloendotheliosis, Systemic Aleukemic",
        "Systemic Aleukemic Reticuloendothelioses",
        "Type 2 Histiocytosis",
        "Histiocytoses, Type 2",
        "Histiocytosis, Type 2",
        "Type 2 Histiocytoses",
        "Langerhans Cell Granulomatosis",
        "Cell Granulomatoses, Langerhans",
        "Cell Granulomatosis, Langerhans",
        "Granulomatoses, Langerhans Cell",
        "Granulomatosis, Langerhans Cell",
        "Langerhans Cell Granulomatoses",
        "Hand-Schueller-Christian Disease",
        "Disease, Hand-Schueller-Christian",
        "Hand Schueller Christian Disease",
        "Pulmonary Histiocytosis X",
        "Histiocytosis X, Pulmonary",
        "Pulmonary Langerhans Cell Granulomatosis",
        "Langerhans Cell Granulomatosis, Pulmonary",
        "Hashimoto-Pritzger Disease",
        "Eosinophilic Granuloma"
        # Myelodysplastic Syndromes
        "Myelodysplastic Syndrome",
        "Syndrome, Myelodysplastic",
        "Syndromes, Myelodysplastic",
        "Dysmyelopoietic Syndromes",
        "Dysmyelopoietic Syndrome",
        "Syndrome, Dysmyelopoietic",
        "Syndromes, Dysmyelopoietic",
        "Hematopoetic Myelodysplasia",
        "Hematopoetic Myelodysplasias",
        "Myelodysplasia, Hematopoetic",
        "Myelodysplasias, Hematopoetic"
        # hematologic neoplasms
        "Hematologic Neoplasm",
        "Neoplasm, Hematologic",
        "Hematologic Malignancies",
        "Hematologic Malignancy",
        "Neoplasms, Hematologic",
        "Hematological Neoplasms",
        "Hematological Neoplasm",
        "Neoplasm, Hematological",
        "Malignancies, Hematologic",
        "Malignancy, Hematologic",
        "Blood Cancer",
        "Blood Cancers",
        "Cancer, Blood",
        "Hematological Malignancies",
        "Hematological Malignancy",
        "Malignancy, Hematological",
        "Hematopoietic Neoplasms",
        "Hematopoietic Neoplasm",
        "Neoplasm, Hematopoietic",
        "Neoplasms, Hematopoietic",
        "Hematopoietic Malignancies",
        "Hematopoietic Malignancy",
        "Malignancy, Hematopoietic",
        "Neoplasms, Bone Marrow",
        "Bone Marrow Neoplasm",
        "Neoplasm, Bone Marrow",
        "Primary Polycythemia",
        "Polycythemia, Primary",
        "Polycythemias, Primary",
        "Primary Polycythemias",
        "Polycythemia Rubra Vera",
        "Polycythemia Rubra Veras",
        "Vera, Polycythemia Rubra",
        "Veras, Polycythemia Rubra",
        "Polycythemia Ruba Vera",
        "Polycythemia Ruba Veras",
        "Ruba Vera, Polycythemia",
        "Ruba Veras, Polycythemia",
        "Vera, Polycythemia Ruba",
        "Veras, Polycythemia Ruba",
        "Osler-Vaquez Disease",
        "Disease, Osler-Vaquez",
        "Osler Vaquez Disease"
        # Bone Cancer
        "Bone Neoplasm",
        "Neoplasm, Bone",
        "Neoplasms, Bone",
        "Bone Cancer",
        "Cancer of the Bone",
        "Cancer of Bone",
        "Adamantinomas",
        "Adamantinoma"
        # Ewing Sarcoma
        "Sarcoma, Ewing's",
        "Sarcoma, Ewings",
        "Ewing's Sarcoma",
        "Ewings Sarcoma",
        "Ewing's Tumor",
        "Ewings Tumor",
        "Tumor, Ewing's",
        "Ewing Sarcoma",
        "Ewing Tumor",
        "Tumor, Ewing"
        # Osteosarcoma and Undifferentiated Pleomorphic Sarcoma of Bone Treatment
        "Osteosarcomas",
        "Osteosarcoma Tumor",
        "Osteosarcoma Tumors",
        "Tumor, Osteosarcoma",
        "Tumors, Osteosarcoma",
        "Sarcoma, Osteogenic",
        "Osteogenic Sarcomas",
        "Sarcomas, Osteogenic",
        "Osteogenic Sarcoma",
        "Osteosarcoma, Juxtacortical",
        "Sarcoma, Ewing"
        # Chordoma
        "Chordoma",
        # Rhabdomyosarcoma
        "Rhabdomyosarcomas",
        # Soft Tissue Sarcoma
        "Sarcomas",
        "Sarcoma, Soft Tissue",
        "Sarcomas, Soft Tissue",
        "Soft Tissue Sarcoma",
        "Soft Tissue Sarcomas",
        "Sarcoma, Epithelioid",
        "Epithelioid Sarcoma",
        "Epithelioid Sarcomas",
        "Sarcomas, Epithelioid",
        "Sarcoma, Spindle Cell",
        "Sarcomas, Spindle Cell",
        "Spindle Cell Sarcoma",
        "Spindle Cell Sarcomas"
        # Brain Tumor
        "Brain Neoplasm",
        "Neoplasm, Brain",
        "Neoplasms, Brain",
        "Brain Tumors",
        "Brain Tumor",
        "Tumor, Brain",
        "Benign Neoplasms, Brain",
        "Benign Neoplasm, Brain",
        "Brain Benign Neoplasm",
        "Brain Benign Neoplasms",
        "Neoplasms, Brain, Benign",
        "Brain Neoplasms, Benign",
        "Benign Brain Neoplasm",
        "Benign Brain Neoplasms",
        "Brain Neoplasm, Benign",
        "Neoplasms, Intracranial",
        "Intracranial Neoplasm",
        "Neoplasm, Intracranial",
        "Intracranial Neoplasms",
        "Brain Tumor, Primary",
        "Primary Brain Tumor",
        "Primary Brain Tumors",
        "Neoplasms, Brain, Primary",
        "Brain Neoplasm, Primary",
        "Primary Brain Neoplasms",
        "Brain Neoplasms, Primary",
        "Primary Brain Neoplasm",
        "Brain Tumor, Recurrent",
        "Brain Tumors, Recurrent",
        "Recurrent Brain Tumor",
        "Recurrent Brain Tumors",
        "Malignant Primary Brain Tumors",
        "Primary Malignant Brain Tumors",
        "Malignant Primary Brain Neoplasms",
        "Primary Malignant Brain Neoplasms",
        "Brain Neoplasms, Malignant, Primary",
        "Brain Neoplasms, Primary Malignant",
        "Brain Metastases",
        "Brain Metastase",
        "Brain Cancer",
        "Brain Cancers",
        "Cancer, Brain",
        "Malignant Neoplasms, Brain",
        "Brain Malignant Neoplasm",
        "Brain Malignant Neoplasms",
        "Malignant Neoplasm, Brain",
        "Cancer of Brain",
        "Cancer of the Brain",
        "Neoplasms, Brain, Malignant",
        "Brain Neoplasms, Malignant",
        "Brain Neoplasm, Malignant",
        "Malignant Brain Neoplasm",
        "Malignant Brain Neoplasms",
        "Cerebroventricular Neoplasms",
        "Cerebroventricular Neoplasm",
        "Neoplasm, Cerebroventricular",
        "Neoplasms, Cerebroventricular",
        "Intraventricular Neoplasms",
        "Intraventricular Neoplasm",
        "Neoplasm, Intraventricular",
        "Cerebral Ventricle Tumors",
        "Cerebral Ventricle Tumor",
        "Tumor, Cerebral Ventricle",
        "Tumors, Cerebral Ventricle",
        "Ventricle Tumor, Cerebral",
        "Ventricle Tumors, Cerebral",
        "Ventricular Tumors, Brain",
        "Brain Ventricular Tumor",
        "Brain Ventricular Tumors",
        "Tumor, Brain Ventricular",
        "Tumors, Brain Ventricular",
        "Ventricular Tumor, Brain",
        "Brain Ventricular Neoplasms",
        "Neoplasms, Intraventricular",
        "Neoplasms, Ventricular, Brain",
        "Neoplasms, Cerebral Ventricle",
        "Cerebral Ventricle Neoplasm",
        "Neoplasm, Cerebral Ventricle",
        "Ventricular Neoplasms, Brain",
        "Brain Ventricular Neoplasm",
        "Neoplasm, Brain Ventricular",
        "Neoplasms, Brain Ventricular",
        "Ventricular Neoplasm, Brain",
        "Choroid Plexus Tumors",
        "Choroid Plexus Tumor",
        "Neoplasms, Choroid Plexus",
        "Choroid Plexus Neoplasm",
        "Neoplasm, Choroid Plexus",
        "Choroid Plexus Neoplasms, Primary",
        "Primary Choroid Plexus Neoplasms",
        "Choroid Plexus Papillomas",
        "Papillomas, Choroid Plexus",
        "Papilloma of Choroid Plexus",
        "Choroid Plexus Papilloma",
        "Infratentorial Neoplasm",
        "Neoplasm, Infratentorial",
        "Posterior Fossa Tumors",
        "Posterior Fossa Tumor",
        "Tumor, Posterior Fossa",
        "Infratentorial Tumors",
        "Infratentorial Tumor",
        "Tumor, Infratentorial",
        "Posterior Fossa Neoplasms",
        "Neoplasm, Posterior Fossa",
        "Posterior Fossa Neoplasm",
        "Neoplasms, Posterior Fossa",
        "Neoplasms, Infratentorial",
        "Infratentorial Cancer",
        "Cancer, Infratentorial",
        "Infratentorial Cancers",
        "Infratentorial Neoplasms, Malignant",
        "Infratentorial Neoplasm, Malignant",
        "Malignant Infratentorial Neoplasm",
        "Neoplasm, Malignant Infratentorial",
        "Neoplasms, Malignant Infratentorial",
        "Malignant Infratentorial Neoplasms",
        "Benign Infratentorial Neoplasms",
        "Infratentorial Neoplasms, Benign",
        "Benign Infratentorial Neoplasm",
        "Infratentorial Neoplasm, Benign",
        "Neoplasm, Benign Infratentorial",
        "Brain Stem Neoplasm",
        "Neoplasm, Brain Stem",
        "Neoplasms, Brain Stem",
        "Brainstem Neoplasms",
        "Brainstem Neoplasm",
        "Neoplasm, Brainstem",
        "Brainstem Tumors",
        "Brainstem Tumor",
        "Neoplasms, Brainstem",
        "Brain Stem Tumors",
        "Brain Stem Tumor",
        "Tumor, Brain Stem",
        "Pontine Tumors",
        "Pontine Tumor",
        "Tumor, Pontine",
        "Tumors, Pontine",
        "Pontine Neoplasms",
        "Neoplasms, Pontine",
        "Neoplasm, Pontine",
        "Pontine Neoplasm",
        "Mesencephalic Neoplasms",
        "Mesencephalic Neoplasm",
        "Neoplasm, Mesencephalic",
        "Neoplasms, Midbrain",
        "Midbrain Tumors",
        "Midbrain Tumor",
        "Tumor, Midbrain",
        "Tumors, Midbrain",
        "Midbrain Neoplasms",
        "Midbrain Neoplasm",
        "Neoplasm, Midbrain",
        "Neoplasms, Mesencephalic",
        "Brain Stem Neoplasms, Primary",
        "Primary Brainstem Neoplasms",
        "Primary Brain Stem Neoplasms",
        "Brainstem Neoplasms, Primary",
        "Brainstem Neoplasm, Primary",
        "Neoplasm, Primary Brainstem",
        "Neoplasms, Primary Brainstem",
        "Primary Brainstem Neoplasm",
        "Neoplasms, Brainstem, Primary",
        "Medullary Neoplasms",
        "Medullary Neoplasm",
        "Neoplasm, Medullary",
        "Neoplasms, Medullary",
        "Medullary Tumors",
        "Medullary Tumor",
        "Tumor, Medullary",
        "Tumors, Medullary",
        "Cerebellar Tumors",
        "Cerebellar Tumor",
        "Tumor, Cerebellar",
        "Neoplasms, Cerebellar",
        "Cerebellar Neoplasm",
        "Neoplasm, Cerebellar",
        "Cerebellar Neoplasms, Primary",
        "Cerebellar Neoplasm, Primary",
        "Primary Cerebellar Neoplasm",
        "Primary Cerebellar Neoplasms",
        "Primary Neoplasms, Cerebellum",
        "Cerebellum Primary Neoplasm",
        "Cerebellum Primary Neoplasms",
        "Neoplasm, Cerebellum Primary",
        "Primary Neoplasm, Cerebellum",
        "Neoplasms, Cerebellar, Primary",
        "Benign Cerebellar Neoplasms",
        "Benign Cerebellar Neoplasm",
        "Cerebellar Neoplasm, Benign",
        "Neoplasm, Benign Cerebellar",
        "Neoplasms, Cerebellar, Benign",
        "Cerebellar Neoplasms, Benign",
        "Cerebellar Cancer",
        "Cancer, Cerebellar",
        "Cerebellar Cancers",
        "Cerebellar Neoplasms, Malignant",
        "Neoplasms, Cerebellar, Malignant",
        "Malignant Cerebellar Neoplasms",
        "Cerebellar Neoplasm, Malignant",
        "Malignant Cerebellar Neoplasm",
        "Neoplasm, Malignant Cerebellar",
        "Neurocytomas",
        "Neurocytoma, Central",
        "Central Neurocytoma",
        "Central Neurocytomas",
        "Neurocytomas, Central",
        "Pinealomas",
        "Pineal Gland Tumor",
        "Pineal Gland Tumors",
        "Tumor, Pineal Gland",
        "Tumors, Pineal Gland",
        "Pineal Parenchymal Tumors",
        "Pineal Parenchymal Tumor",
        "Tumor, Pineal Parenchymal",
        "Tumors, Pineal Parenchymal",
        "Pineal Tumors",
        "Pineal Tumor",
        "Tumor, Pineal",
        "Tumors, Pineal",
        "Neoplasms, Pineal",
        "Neoplasm, Pineal",
        "Pineal Neoplasm",
        "Pineal Neoplasms",
        "Pineoblastoma",
        "Pineoblastomas",
        "Mixed Pineocytoma-Pineoblastoma",
        "Mixed Pineocytoma Pineoblastoma",
        "Mixed Pineocytoma-Pineoblastomas",
        "Pineocytoma-Pineoblastoma, Mixed",
        "Pineocytoma-Pineoblastomas, Mixed",
        "Pinealocytoma",
        "Pinealocytomas",
        "Pineocytoma",
        "Pineocytomas",
        "Supratentorial Tumors",
        "Supratentorial Tumor",
        "Tumor, Supratentorial",
        "Tumors, Supratentorial",
        "Neoplasms, Supratentorial",
        "Neoplasm, Supratentorial",
        "Supratentorial Neoplasm",
        "Cancer, Supratentorial",
        "Cancers, Supratentorial",
        "Supratentorial Cancer",
        "Supratentorial Cancers",
        "Supratentorial Neoplasms, Malignant",
        "Malignant Supratentorial Neoplasms",
        "Malignant Supratentorial Neoplasm",
        "Neoplasm, Malignant Supratentorial",
        "Neoplasms, Malignant Supratentorial",
        "Supratentorial Neoplasm, Malignant",
        "Primary Supratentorial Neoplasms",
        "Neoplasm, Primary Supratentorial",
        "Neoplasms, Primary Supratentorial",
        "Primary Supratentorial Neoplasm",
        "Supratentorial Neoplasm, Primary",
        "Supratentorial Neoplasms, Primary",
        "Benign Supratentorial Neoplasms",
        "Benign Supratentorial Neoplasm",
        "Neoplasm, Benign Supratentorial",
        "Neoplasms, Benign Supratentorial",
        "Supratentorial Neoplasm, Benign",
        "Supratentorial Neoplasms, Benign",
        "Hypothalamus Neoplasms",
        "Hypothalamus Neoplasm",
        "Neoplasm, Hypothalamus",
        "Tumors, Hypothalamus",
        "Hypothalamus Tumor",
        "Hypothalamus Tumors",
        "Tumor, Hypothalamus",
        "Neoplasms, Hypothalamus",
        "Hypothalamic Tumors",
        "Hypothalamic Tumor",
        "Tumor, Hypothalamic",
        "Tumors, Hypothalamic",
        "Neoplasms, Hypothalamic",
        "Hypothalamic Neoplasm",
        "Neoplasm, Hypothalamic",
        "Hypothalamic Cancer",
        "Cancer, Hypothalamic",
        "Cancers, Hypothalamic",
        "Hypothalamic Cancers",
        "Hypothalamic Neoplasms, Malignant",
        "Hypothalamic Neoplasm, Malignant",
        "Malignant Hypothalamic Neoplasm",
        "Neoplasm, Malignant Hypothalamic",
        "Neoplasms, Malignant Hypothalamic",
        "Malignant Hypothalamic Neoplasms",
        "Neoplasms, Hypothalamic, Malignant",
        "Hypothalamic-Pituitary Neoplasms",
        "Hypothalamic Pituitary Neoplasms",
        "Hypothalamic-Pituitary Neoplasm",
        "Neoplasm, Hypothalamic-Pituitary",
        "Neoplasms, Hypothalamic-Pituitary",
        "Neoplasms, Hypothalamic Pituitary",
        "Neoplasms, Hypothalamo-Neurohypophysial Region",
        "Neoplasms, Hypothalamo Neurohypophysial Region",
        "Hypothalamo-Neurohypophysial Region Neoplasms",
        "Hypothalamo Neurohypophysial Region Neoplasms",
        "Hypothalamo-Neurohypophysial Region Neoplasm",
        "Neoplasm, Hypothalamo-Neurohypophysial Region",
        "Hypothalamic Teratomas",
        "Hypothalamic Teratoma",
        "Teratoma, Hypothalamic",
        "Teratomas, Hypothalamic",
        "Hypothalamic-Chiasmatic Neoplasms",
        "Hypothalamic Chiasmatic Neoplasms",
        "Hypothalamic-Chiasmatic Neoplasm",
        "Neoplasm, Hypothalamic-Chiasmatic",
        "Neoplasms, Hypothalamic-Chiasmatic",
        "Neoplasms, Hypothalamic Chiasmatic",
        "Benign Hypothalamic Neoplasms",
        "Benign Hypothalamic Neoplasm",
        "Neoplasm, Benign Hypothalamic",
        "Neoplasms, Hypothalamic, Benign",
        "Hypothalamic Neoplasms, Benign"
        # Astrocytomas
        "Astrocytomas",
        "Astroglioma",
        "Astrogliomas",
        "Glioma, Astrocytic",
        "Astrocytic Glioma",
        "Astrocytic Gliomas",
        "Gliomas, Astrocytic",
        "Astrocytoma, Grade I",
        "Grade I Astrocytoma",
        "Grade I Astrocytomas",
        "Astrocytoma, Grade II",
        "Grade II Astrocytoma",
        "Grade II Astrocytomas",
        "Pleomorphic Xanthoastrocytomas",
        "Pleomorphic Xanthoastrocytoma",
        "Xanthoastrocytoma, Pleomorphic",
        "Astrocytoma, Protoplasmic",
        "Protoplasmic Astrocytoma",
        "Protoplasmic Astrocytomas",
        "Astrocytoma, Subependymal Giant Cell",
        "Subependymal Giant Cell Astrocytoma",
        "Intracranial Astrocytoma",
        "Astrocytoma, Intracranial",
        "Intracranial Astrocytomas",
        "Oligoastrocytoma, Mixed",
        "Mixed Oligoastrocytoma",
        "Mixed Oligoastrocytomas",
        "Pilocytic Astrocytoma",
        "Astrocytoma, Pilocytic",
        "Pilocytic Astrocytomas",
        "Cerebral Astrocytoma",
        "Astrocytoma, Cerebral",
        "Cerebral Astrocytomas",
        "Childhood Cerebral Astrocytoma",
        "Astrocytoma, Childhood Cerebral",
        "Cerebral Astrocytoma, Childhood",
        "Childhood Cerebral Astrocytomas",
        "Fibrillary Astrocytoma",
        "Astrocytoma, Fibrillary",
        "Fibrillary Astrocytomas",
        "Gemistocytic Astrocytoma",
        "Astrocytoma, Gemistocytic",
        "Gemistocytic Astrocytomas",
        "Anaplastic Astrocytoma",
        "Anaplastic Astrocytomas",
        "Astrocytoma, Anaplastic",
        "Astrocytoma, Grade III",
        "Astrocytomas, Grade III",
        "Grade III Astrocytoma",
        "Grade III Astrocytomas",
        "Juvenile Pilocytic Astrocytoma",
        "Astrocytoma, Juvenile Pilocytic",
        "Juvenile Pilocytic Astrocytomas",
        "Pilocytic Astrocytoma, Juvenile",
        "Glioblastomas",
        "Astrocytoma, Grade IV",
        "Astrocytomas, Grade IV",
        "Grade IV Astrocytoma",
        "Grade IV Astrocytomas",
        "Glioblastoma Multiforme",
        "Giant Cell Glioblastoma",
        "Giant Cell Glioblastomas",
        "Glioblastoma, Giant Cell",
        "Glioblastomas, Giant Cell"
        # Brain Stem Glioma
        "Gliomas",
        "Glial Cell Tumors",
        "Glial Cell Tumor",
        "Tumor, Glial Cell",
        "Tumors, Glial Cell",
        "Mixed Glioma",
        "Glioma, Mixed",
        "Gliomas, Mixed",
        "Mixed Gliomas",
        "Malignant Glioma",
        "Glioma, Malignant",
        "Gliomas, Malignant",
        "Malignant Gliomas"
        # Central Nervous System Atypical Teratoid/Rhabdoid Tumor
        "Rhabdoid Tumors",
        "Tumor, Rhabdoid",
        "Tumors, Rhabdoid",
        "Teratomas",
        "Dysembryoma",
        "Dysembryomas",
        "Teratoid Tumor",
        "Teratoid Tumors",
        "Tumor, Teratoid",
        "Tumors, Teratoid",
        "Teratoma, Benign",
        "Benign Teratoma",
        "Benign Teratomas",
        "Teratomas, Benign",
        "Teratoma, Mature",
        "Teratoma, Cystic",
        "Teratoma, Malignant",
        "Malignant Teratoma",
        "Malignant Teratomas",
        "Teratomas, Malignant",
        "Teratoma, Immature",
        "Immature Teratoma",
        "Immature Teratomas",
        "Teratomas, Immature"
        # Medulloblastoma and Other Central Nervous System Embryonal Tumors
        "Medulloblastomas",
        "Melanocytic Medulloblastoma",
        "Medulloblastoma, Melanocytic",
        "Medulloblastomas, Melanocytic",
        "Melanocytic Medulloblastomas",
        "Medulloblastoma, Childhood",
        "Childhood Medulloblastoma",
        "Childhood Medulloblastomas",
        "Medulloblastomas, Childhood",
        "Medullomyoblastoma",
        "Medullomyoblastomas",
        "Arachnoidal Cerebellar Sarcoma, Circumscribed",
        "Sarcoma, Cerebellar, Circumscribed Arachnoidal",
        "Medulloblastoma, Desmoplastic",
        "Desmoplastic Medulloblastoma",
        "Desmoplastic Medulloblastomas",
        "Medulloblastomas, Desmoplastic",
        "Medulloblastoma, Adult",
        "Adult Medulloblastoma",
        "Adult Medulloblastomas",
        "Medulloblastomas, Adult"
        # Craniopharyngioma
        "Craniopharyngiomas",
        "Neoplasm, Rathke's Cleft",
        "Neoplasm, Rathkes Cleft",
        "Rathke's Pouch Tumor",
        "Rathkes Pouch Tumor",
        "Tumor, Rathke's Pouch",
        "Rathke Pouch Tumor",
        "Tumor, Rathke Pouch",
        "Rathke's Cleft Neoplasm",
        "Rathkes Cleft Neoplasm",
        "Neoplasm, Rathke Cleft",
        "Rathke Cleft Neoplasm",
        "Craniopharyngioma, Papillary",
        "Craniopharyngiomas, Papillary",
        "Papillary Craniopharyngioma",
        "Papillary Craniopharyngiomas",
        "Craniopharyngioma, Child",
        "Child Craniopharyngioma",
        "Child Craniopharyngiomas",
        "Craniopharyngiomas, Child",
        "Craniopharyngioma, Adamantinous",
        "Adamantinous Craniopharyngioma",
        "Adamantinous Craniopharyngiomas",
        "Craniopharyngiomas, Adamantinous",
        "Craniopharyngioma, Adult",
        "Adult Craniopharyngioma",
        "Adult Craniopharyngiomas",
        "Craniopharyngiomas, Adult"
        # Ependymoma
        "Ependymomas",
        "Ependymoma, Papillary",
        "Ependymomas, Papillary",
        "Papillary Ependymomas",
        "Papillary Ependymoma",
        "Ependymoma, Myxopapillary",
        "Ependymomas, Myxopapillary",
        "Myxopapillary Ependymoma",
        "Myxopapillary Ependymomas",
        "Anaplastic Ependymoma",
        "Anaplastic Ependymomas",
        "Ependymoma, Anaplastic",
        "Ependymomas, Anaplastic",
        "Cellular Ependymoma",
        "Clear Cell Ependymoma",
        # Neuroblastoma
        "Neuroblastomas",
        "Esthesioneuroblastoma, Olfactory",
        "Ganglioneuroblastoma",
        # Lung Cancer, Non-Small Cell
        "Carcinoma, Non Small Cell Lung",
        "Carcinomas, Non-Small-Cell Lung",
        "Lung Carcinoma, Non-Small-Cell",
        "Lung Carcinomas, Non-Small-Cell",
        "Non-Small-Cell Lung Carcinomas",
        "Non-Small-Cell Lung Carcinoma",
        "Non Small Cell Lung Carcinoma",
        "Carcinoma, Non-Small Cell Lung",
        "Non-Small Cell Lung Carcinoma",
        "Non-Small Cell Lung Cancer",
        "Nonsmall Cell Lung Cancer",
        # Lung Cancer, Small Cell
        "Small Cell Lung Cancer",
        "Oat Cell Lung Cancer",
        "Small Cell Cancer Of The Lung",
        "Carcinoma, Small Cell Lung",
        "Oat Cell Carcinoma of Lung",
        # Malignant Mesothelioma
        "Malignant Mesotheliomas",
        "Mesotheliomas, Malignant",
        "Malignant Mesothelioma",
        "Malignant Pleural Mesothelioma",
        "Malignant Pleural Mesotheliomas",
        "Mesotheliomas, Malignant Pleural",
        "Pleural Mesothelioma, Malignant",
        "Pleural Mesotheliomas, Malignant",
        "Mesothelioma, Malignant Pleural",
        # Thymoma and Thymic Carcinoma
        "Thymomas",
        "Carcinoma, Thymic",
        "Carcinomas, Thymic",
        "Thymic Carcinoma",
        "Thymic Carcinomas",
        # T-Cell Lymphoma, Cutaneous
        "Lymphoma, T Cell, Cutaneous",
        "T-Cell Lymphoma, Cutaneous",
        "T Cell Lymphoma, Cutaneous",
        "Cutaneous T-Cell Lymphoma",
        "Cutaneous T Cell Lymphoma",
        "Cutaneous T-Cell Lymphomas",
        "Lymphoma, Cutaneous T-Cell",
        "Lymphomas, Cutaneous T-Cell",
        "T-Cell Lymphomas, Cutaneous",
        "Granulomatous Slack Skin",
        "Slack Skin, Granulomatous"
        # neoplasms, unknown primary
        "Occult Primary Neoplasms",
        "Neoplasms, Occult Primary",
        "Neoplasm, Occult Primary",
        "Occult Primary Neoplasm",
        "Primary Neoplasm, Occult",
        "Primary Neoplasms, Occult",
        "Unknown Primary Neoplasms",
        "Neoplasm, Unknown Primary",
        "Primary Neoplasm, Unknown",
        "Primary Neoplasms, Unknown",
        "Unknown Primary Neoplasm",
        "Unknown Primary Tumors",
        "Primary Tumor, Unknown",
        "Primary Tumors, Unknown",
        "Tumor, Unknown Primary",
        "Tumors, Unknown Primary",
        "Unknown Primary Tumor",
        "Neoplasm Metastasis, Unknown Primary",
        "Unknown Primary Neoplasm Metastasis"
        # Melanoma
        "Melanomas",
        "Malignant Melanoma",
        "Malignant Melanomas",
        "Melanoma, Malignant",
        "Melanomas, Malignant",
        "Melanoma, Amelanotic",
        # Skin Cancer
        "Neoplasms, Skin",
        "Neoplasm, Skin",
        "Skin Neoplasm",
        "Cancer of Skin",
        "Skin Cancers",
        "Cancer of the Skin",
        "Skin Cancer",
        "Cancer, Skin",
        "Cancers, Skin",
        "Acanthoma",
        "Mastocytosis, Cutaneous",
        "Mastocytoma, Skin",
        "Urticaria Pigmentosa",
        "Sebaceous Gland Neoplasms",
        "Muir-Torre Syndrome",
        "Sweat Gland Neoplasms"
        # Anal Cancer
        "Neoplasms, Anal",
        "Anal Neoplasms",
        "Anal Neoplasm",
        "Neoplasm, Anal",
        "Neoplasms, Anus",
        "Anus Neoplasm",
        "Neoplasm, Anus",
        "Anal Cancer",
        "Anal Cancers",
        "Cancer, Anal",
        "Cancers, Anal",
        "Cancer of the Anus",
        "Cancer of Anus",
        "Anus Cancer",
        "Anus Cancers"
        # Appendix Cancer
        "Appendiceal Neoplasm",
        "Neoplasm, Appendiceal",
        "Neoplasms, Appendiceal",
        "Appendiceal Cancer",
        "Cancer, Appendiceal",
        "Cancer of the Appendix",
        "Appendix Cancer",
        "Cancer, Appendix",
        "Cancer of Appendix"
        # Bile Duct Cancer
        "Bile Duct Neoplasm",
        "Neoplasm, Bile Duct",
        "Neoplasms, Bile Duct",
        "Bile Duct Cancer",
        "Bile Duct Cancers",
        "Cancer, Bile Duct",
        "Cancers, Bile Duct",
        "Cancer of the Bile Duct",
        "Cancer of Bile Duct"
        # Colon Cancer
        "Colonic Neoplasm",
        "Neoplasm, Colonic",
        "Neoplasms, Colonic",
        "Colon Neoplasms",
        "Colon Neoplasm",
        "Neoplasm, Colon",
        "Neoplasms, Colon",
        "Cancer of Colon",
        "Colon Cancers",
        "Colon Cancer",
        "Cancer, Colon",
        "Cancers, Colon",
        "Cancer of the Colon",
        "Colonic Cancer",
        "Cancer, Colonic",
        "Cancers, Colonic",
        "Colonic Cancers",
        "Colon Adenocarcinoma",
        "Adenocarcinoma, Colon",
        "Adenocarcinomas, Colon",
        "Colon Adenocarcinomas"
        # Esophageal Cancer
        "Esophageal Neoplasm",
        "Neoplasm, Esophageal",
        "Esophagus Neoplasm",
        "Esophagus Neoplasms",
        "Neoplasm, Esophagus",
        "Neoplasms, Esophagus",
        "Neoplasms, Esophageal",
        "Cancer of Esophagus",
        "Cancer of the Esophagus",
        "Esophagus Cancer",
        "Cancer, Esophagus",
        "Cancers, Esophagus",
        "Esophagus Cancers",
        "Esophageal Cancer",
        "Cancer, Esophageal",
        "Cancers, Esophageal",
        "Esophageal Cancers",
        "Esophageal Squamous Cell Carcinoma",
        # Gallbladder Cancer
        "Gallbladder Neoplasm",
        "Neoplasm, Gallbladder",
        "Neoplasms, Gallbladder",
        "Cancer of Gallbladder",
        "Gallbladder Cancers",
        "Gallbladder Cancer",
        "Cancer, Gallbladder",
        "Cancers, Gallbladder",
        "Gall Bladder Cancer",
        "Bladder Cancer, Gall",
        "Bladder Cancers, Gall",
        "Cancer, Gall Bladder",
        "Cancers, Gall Bladder",
        "Gall Bladder Cancers",
        "Cancer of the Gallbladder",
        "Cholangiocarcinoma"
        # Gastrointestinal Stromal Tumors (GIST)
        "Stromal Tumor, Gastrointestinal",
        "Stromal Tumors, Gastrointestinal",
        "Tumor, Gastrointestinal Stromal",
        "Tumors, Gastrointestinal Stromal",
        "Gastrointestinal Stromal Neoplasms",
        "Neoplasm, Gastrointestinal Stromal",
        "Neoplasms, Gastrointestinal Stromal",
        "Stromal Neoplasm, Gastrointestinal",
        "Stromal Neoplasms, Gastrointestinal",
        "Gastrointestinal Stromal Tumor",
        "Gastrointestinal Stromal Neoplasm",
        "Gastrointestinal Stromal Sarcoma"
        # Islet Cell Tumors, Pancreatic Neuroendocrine Tumors
        "Adenomas, Islet Cell",
        "Islet Cell Adenoma",
        "Islet Cell Adenomas",
        "Islet Cell Tumor",
        "Islet Cell Tumors",
        "Tumor, Islet Cell",
        "Tumors, Islet Cell",
        "Islet of Langerhans Tumor",
        "Langerhans Tumor Islet",
        "Tumor Islet, Langerhans",
        "Island Cell Tumor",
        "Island Cell Tumors",
        "Tumor, Island Cell",
        "Tumors, Island Cell",
        "Pancreatic Islet Cell Tumors",
        "Nesidioblastoma",
        "Nesidioblastomas"
        # Liver Cancer
        "Neoplasms, Hepatic",
        "Neoplasms, Liver",
        "Liver Neoplasm",
        "Neoplasm, Liver",
        "Hepatic Neoplasms",
        "Hepatic Neoplasm",
        "Neoplasm, Hepatic",
        "Cancer of Liver",
        "Hepatocellular Cancer",
        "Cancers, Hepatocellular",
        "Hepatocellular Cancers",
        "Hepatic Cancer",
        "Cancer, Hepatic",
        "Cancers, Hepatic",
        "Hepatic Cancers",
        "Liver Cancer",
        "Cancer, Liver",
        "Cancers, Liver",
        "Liver Cancers",
        "Cancer of the Liver",
        "Cancer, Hepatocellular"
        # Pancreatic Cancer
        "Neoplasm, Pancreatic",
        "Pancreatic Neoplasm",
        "Pancreas Neoplasms",
        "Neoplasm, Pancreas",
        "Neoplasms, Pancreas",
        "Pancreas Neoplasm",
        "Neoplasms, Pancreatic",
        "Cancer of Pancreas",
        "Pancreas Cancers",
        "Pancreas Cancer",
        "Cancer, Pancreas",
        "Cancers, Pancreas",
        "Pancreatic Cancer",
        "Cancer, Pancreatic",
        "Cancers, Pancreatic",
        "Pancreatic Cancers",
        "Cancer of the Pancreas",
        "Adenoma, Islet Cell",
        "Insulinoma",
        "Carcinoma, Islet Cell",
        "Gastrinoma",
        "Glucagonoma",
        "Somatostatinoma",
        "Vipoma",
        "Carcinoma, Pancreatic Ductal",
        "Pancreatic Intraductal Neoplasms"
        # Rectal Cancer
        "Neoplasm, Rectal",
        "Rectal Neoplasm",
        "Rectum Neoplasms",
        "Neoplasm, Rectum",
        "Rectum Neoplasm",
        "Rectal Tumors",
        "Rectal Tumor",
        "Tumor, Rectal",
        "Neoplasms, Rectal",
        "Cancer of Rectum",
        "Rectum Cancers",
        "Rectal Cancer",
        "Cancer, Rectal",
        "Rectal Cancers",
        "Rectum Cancer",
        "Cancer, Rectum",
        "Cancer of the Rectum"
        # Stomach (Gastric) Cancer
        "Neoplasm, Stomach",
        "Stomach Neoplasm",
        "Neoplasms, Stomach",
        "Gastric Neoplasms",
        "Gastric Neoplasm",
        "Neoplasm, Gastric",
        "Neoplasms, Gastric",
        "Cancer of Stomach",
        "Stomach Cancers",
        "Gastric Cancer",
        "Cancer, Gastric",
        "Cancers, Gastric",
        "Gastric Cancers",
        "Stomach Cancer",
        "Cancer, Stomach",
        "Cancers, Stomach",
        "Cancer of the Stomach",
        "Gastric Cancer, Familial Diffuse",
    ]
]
