cancer_keywords = [
    word.lower()
    for word in [
        # AIDS-Related Lymphoma
        "AIDS Associated Lymphoma",
        "HIV Associated Lymphoma",
        "AIDS Related Lymphoma",
        "HIV Related Lymphoma",
        "AIDS-Related Lymphoma",
        "HIV-Related Lymphoma",
        "AIDS-Associated Lymphoma",
        "HIV-Associated Lymphoma",
        # eye neoplasms
        "Eye Cancer",
        "Eye Neoplasm",
        "Cancer of Eye",
        "Cancer of the Eye",
        "Conjunctival Neoplasm",
        "Conjunctival cancer",
        "Intraocular Lymphoma",
        "Orbital Neoplasm",
        "Orbital cancer",
        "Ocular Paraneoplastic Syndrome",
        "Retinal Neoplasm",
        "Retinal cancer",
        "Retinoblastoma",
        "Uveal Neoplasm",
        "Uveal cancer",
        "Choroid Neoplasm",
        "Choroid cancer",
        "Iris Neoplasm",
        "Iris cancer",
        # Wilms Tumor and Other Childhood Kidney Tumors
        "Wilm Tumor",
        "Wilms' Tumor",
        "Wilm's Tumor",
        "Wilm Tumour",
        "Wilms' Tumour",
        "Wilm's Tumour",
        "Nephroblastoma",
        "Denys-Drash Syndrome",
        "WAGR Syndrome",
        # Ovarian Tumors
        "Ovarian Epithelial Carcinoma",
        "Granulosa Cell Tumor",
        "Granulosa Cell Tumour",
        "Hereditary Breast and Ovarian Cancer Syndrome",
        "Luteoma",
        "Meigs Syndrome",
        "Meig's Syndrome",
        "Sertoli-Leydig Cell Tumor",
        "Sertoli-Leydig Cell Tumour",
        "Thecoma",
        "Krukenberg Tumor",
        "Krukenberg Tumour",
        "Brenner Tumor",
        "Brenner Tumour",
        # Primary Peritoneal Cancer
        "Peritoneal Neoplasm",
        "Peritoneal cancer",
        "Peritoneal Surface Malignancy",
        "Peritoneal Malignancy",
        "Peritoneal Surface Malignancies",
        "Peritoneal Malignancies",
        "Peritoneal Carcinomatosis",
        "Peritoneal Carcinomatoses",
        "Pseudomyxoma Peritonei",
        # Vaginal Cancer
        "Vaginal Neoplasm",
        "Vaginal Cancer",
        "Cancer of the Vagina",
        "Cancer of Vagina",
        "Vagina Cancers",
        "Vagina Cancer",
        # Vulvar Cancer
        "Vulvar Neoplasm",
        "Vulva Neoplasm",
        "Cancer of Vulva",
        "Cancer of the Vulva",
        "Vulva Cancer",
        "Vulvar Cancer",
        # head and neck neoplasms
        "Head, Neck Neoplasms",
        "Head and Neck Neoplasm",
        "Cancer of Head and Neck",
        "Head and Neck Cancer",
        "Cancer of the Head and Neck",
        "Upper Aerodigestive Tract Neoplasms",
        "Head Neoplasm",
        "Head Cancer",
        "Cancer of Head",
        "Cancer of the Head",
        "Neck Neoplasm",
        "Cancer of Neck",
        "Neck Cancer",
        "Cancer of the Neck",
        "Esophageal Neoplasm",
        "Esophagus Neoplasm",
        "Cancer of Esophagus",
        "Cancer of the Esophagus",
        "Esophagus Cancer",
        "Esophageal Cancer",
        "Esophageal Squamous Cell Carcinoma",
        # Facial
        "Facial Neoplasm",
        "Eyelid Neoplasm",
        # Oral/Oropharyngeal Cancer
        "Mouth Neoplasm",
        "Oral Neoplasm",
        "Cancer of Mouth",
        "Mouth Cancers",
        "Oral Cancer",
        "Cancer of the Mouth",
        "Mouth Cancer",
        "Gingival Neoplasm",
        "Congenital Epulides",
        "Congenital Epulis",
        "Oral Leukoplakia",
        "Oral Leukokeratoses",
        "Oral Leukokeratosis",
        "Oral Keratoses",
        "Lip Neoplasm",
        "Cancer of Lip",
        "Cancer of the Lip",
        "Lip Cancer",
        "Oropharyngeal Neoplasm",
        "Oropharynx Neoplasm",
        "Cancer of Oropharnyx",
        "Cancer of the Oropharynx",
        "Oropharnyx Cancer",
        "Oropharyngeal Cancer",
        "Tonsil Neoplasm",
        "Tonsillar Neoplasm",
        "Cancer of Tonsil",
        "Cancer of the Tonsil",
        "Tonsil Cancer",
        "Tonsillar Cancer",
        # ENT
        "Otorhinolaryngologic Neoplasm",
        "Ootorhinolaryngeal Neoplasm",
        "Otorhinolaryngological Neoplasm",
        "Otorhinolaryngeal Cancer",
        "Ear Neoplasm",
        "Neoplasms of Ear Auricle",
        "Ear Auricle Neoplasm",
        "Auricular Neoplasm",
        "Cancer of Ear",
        "Ear Cancer",
        "Cancer of the Ear",
        "Ear Auricle Cancer",
        "Auricular Cancer",
        "Laryngeal Neoplasm",
        "Larynx Neoplasm",
        "Cancer of Larynx",
        "Larynx Cancer",
        "Laryngeal Cancer",
        "Cancer of the Larynx",
        "Nose Neoplasm",
        "Nasal Neoplasm",
        "Cancer of Nose",
        "Nose Cancer",
        "Nasal Cancer",
        "Cancer of the Nose",
        "Pharyngeal Neoplasm",
        "Pharynx Neoplasm",
        "Cancer of Pharynx",
        "Pharynx Cancer",
        "Cancer of the Pharynx",
        "Pharyngeal Cancer",
        "Nasopharyngeal Carcinoma",
        "Tonsillar Neoplasm",
        "Head And Neck Squamous Cell Carcinoma",
        "Squamous Cell Carcinoma of the Head and Neck",
        "Squamous Cell Carcinoma of the Larynx",
        "Laryngeal Squamous Cell Carcinoma",
        "Squamous Cell Carcinoma of Larynx",
        "Squamous Cell Carcinoma of the Nasal Cavity",
        "Oral Tongue Squamous Cell Carcinoma",
        "Hypopharyngeal Squamous Cell Carcinoma",
        "Oral Squamous Cell Carcinoma",
        "Oral Cavity Squamous Cell Carcinoma",
        "Squamous Cell Carcinoma of the Mouth",
        "Oropharyngeal Squamous Cell Carcinoma"
        # Salivary Gland Cancer
        "Salivary Gland Neoplasm",
        "Salivary Gland Lymphadenoma",
        "Non-Sebaceous Lymphadenoma",
        "Cancer of Salivary Gland",
        "Cancer of the Salivary Gland",
        "Salivary Gland Cancer",
        "Sebaceous Lymphadenoma",
        "Parotid Neoplasm",
        "Cancer of Parotid",
        "Parotid Cancer",
        "Cancer of the Parotid",
        "Salivary Gland Neoplasm",
        "Salivary Gland Lymphadenoma",
        "Non-Sebaceous Lymphadenoma",
        "Cancer of Salivary Gland",
        "Cancer of the Salivary Gland",
        "Salivary Gland Cancer",
        "Sebaceous Lymphadenoma",
        "Sublingual Gland Neoplasm",
        "Submandibular Gland Neoplasm"
        # Central Nervous System Germ Cell Tumors
        "Germ Cell and Embryonic Neoplasm",
        "Germ Cell and Embryonal Neoplasm",
        "Neoplasms, Germ Cell",
        "Germ Cell Tumor",
        "Germ Cell Tumour",
        "Germ Cell Neoplasm",
        "Embryonal Neoplasm",
        "Embryonal Cancer",
        "Germ Cell Cancer",
        "Embryonal Carcinoma",
        "Chordoma",
        "Germinoma",
        "Dysgerminoma",
        "Disgerminoma",
        "Seminoma",
        "Gonadoblatoma",
        "Mesonephroma",
        "Endodermal Sinus Tumor",
        "Endodermal Sinus Tumour",
        "Yolk Sac Tumor",
        "Yolk Sac Tumour",
        "Neuroectodermal Tumour",
        "Craniopharyngioma",
        "Rathke's Pouch Tumor",
        "Rathke's Pouch Tumour",
        "Rathke's Cleft Neoplasm",
        "Papillary Craniopharyngioma",
        "Adamantinous Craniopharyngioma",
        "Neuroepithelial Tumour",
        "Neuroepithelial Tumor",
        "Neuroepithelial Neoplasm",
        "Polar Spongioblastoma",
        "Gliomatosis Cerebri",
        "Astroblastoma",
        "Ependymoastrocytoma",
        "Melanotic Neuroectodermal Tumor",
        "Melanotic Neuroectodermal Tumour",
        "Retinal Anlage Tumour",
        "Retinal Anlage Tumor",
        "Melanoameloblastoma",
        "Melanotic Progonoma",
        "Neuroendocrine Tumor",
        "Neuroendocrine Tumour",
        "Teratocarcinomas",
        "Teratomas",
        "Dysembryoma",
        "Teratoid Tumour",
        "Benign Teratoma",
        "Malignant Teratoma",
        "Immature Teratoma",
        "Dermoid Cyst",
        "Struma Ovarii",
        "Trophoblastic Neoplasm",
        "Trophoblastic Tumor",
        "Trophoblastic Tumour",
        "Trophoblast Neoplasm",
        "Trophoblast Tumour",
        "Trophoblastic Cancer",
        "Trophoblast Cancer",
        "Choriocarcinomas",
        "Apudoma",
        "Carcinoid Tumor",
        "Malignant Carcinoid Syndrome",
        "Somatostatinoma",
        "Vipoma",
        "Melanoma",
        "Hutchinson's Melanotic Freckle",
        "Neurilemmoma",
        "Acoustic Neuroma",
        "Paraganglioma",
        "Hyatidiform Mole",
        "Pheochromocytoma"
        # Kaposi Sarcoma
        "Kaposi's Sarcoma",
        "Kaposis Sarcoma",
        "Multiple Idiopathic Pigmented Hemangiosarcoma",
        "Kaposi Sarcoma",
        # Breast Cancer
        "Breast Neoplasm",
        "Breast Tumor",
        "Breast Tumour",
        "Breast Cancer",
        "Mammary Cancer",
        "Neoplasm of Breast",
        "Tumour of Breast",
        "Tumor of Breast",
        "Cancer of Breast",
        "Cancer of the Breast",
        "Mammary Carcinoma",
        "Mammary Neoplasm",
        "Breast Carcinoma",
        "Carcinoma of the breast",
        "Paget's Disease of the breast",
        "Hereditary Breast and Ovarian Cancer Syndrome",
        "Inflammatory Breast Neoplasm",
        "Inflammatory Breast cancer",
        "Triple Negative Breast Neoplasm",
        "Triple Negative Breast cancer",
        # endocrine gland neoplasms
        "Endocrine Gland Neoplasm",
        "Carcinoma of Endocrine Gland",
        "Endocrine Gland Carcinoma",
        "Endocrine Cancer",
        "Endocrine Gland Cancer",
        "Cancer of Endocrine Gland",
        "Cancer of the Endocrine Gland",
        "Adrenal Gland Neoplasms",
        "Adrenal Gland cancer",
        "Multiple Endocrine Neoplasia",
        "Ovarian epithelial Carcinoma",
        "Granulosa Cell Tumor",
        "Hereditary Breast and Ovarian Cancer Syndrome",  # look at duplicates in keywords -> can duplicate in dictionary
        "Luteoma",
        "Meigs Syndrome",
        "Sertoli-Leydig Cell Tumor",
        "Sertoli-Leydig Cell Tumour",
        "Thecoma",
        "Islet Cell Adenoma",
        "Islet Cell Carcinoma",
        "Pancreatic Ductal Carcinoma",
        "Pancreatic Intraductal Neoplasm",
        "Parathyroid Neoplasm",
        "Parathyroid cancer",
        "ACTH-Secreting Pituitary Adenoma",
        "Growth Hormone-Secreting Pituitary Adenoma",
        "Prolactinoma",
        "Papillary Thyroid Cancer"
        # carcinoma, neuroendocrine
        "Neuroendocrine Carcinoma",
        "Neuroendocrine Cancer",
        "Medullary Carcinoma",
        "Medullary Cancer",
        "Merkel Cell Cancer",
        "Somatostatinoma",
        "Vipoma",
        # Adrenocortical Carcinoma
        "Adrenocortical Carcinomas",
        "Adrenal Cortical Carcinoma",
        "Adrenal Carcinoma",
        "Adrenal Cancer",
        # Neuroendocrine Carcinoma of the Skin (Merkel Cell Carcinoma)
        "Merkle Tumors",
        "Merkle Tumours",
        "Merkel Cell Tumor",
        "Merkel Cell Tumour",
        "Merkel Cell Cancer",
        "Merkel Cell Carcinoma",
        # Parathyroid Cancer
        "Parathyroid Neoplasm",
        "Parathyroid Adenoma",
        "Parathyroid Carcinoma",
        "Cancer of Parathyroid",
        "Parathyroid Cancer",
        "Cancer of the Parathyroid",
        # Paraganglioma
        "Paragangliomas",
        "Gangliocytic Paraganglioma",
        "Gangliocytic Paragangliomas",
        "Paragangliomata",
        "Carotid Body Tumor",
        "Glomus Jugulare Tumor",
        "Glomus Tympanicum Tumor",
        # Pheochromocytoma
        "Pheochromocytoma",
        # Pituitary Tumor
        "Pituitary Neoplasm",
        "Pituitary Tumor",
        "Pituitary Adenoma",
        "Pituitary Carcinoma",
        "Cancer of the Pituitary",
        "Pituitary Cancer",
        "Cancer of Pituitary",
        "Nelson Syndrome",
        "Prolactinoma"
        # Thyroid Cancer
        "Thyroid Neoplasm",
        "Thyroid Carcinoma",
        "Cancer of Thyroid",
        "Thyroid Cancer",
        "Cancer of the Thyroid",
        "Thyroid Adenoma",
        "Papillary Thyroid Cancer",
        "Papillary Carcinoma Of Thyroid",
        "Papillary Thyroid Carcinoma",
        # Retinoblastoma
        "Retinoblastomas",
        "Retinal Neuroblastoma",
        "Retinal Glioma",
        "Retinal Glioblastoma",
        # Bladder Cancer
        "Urinary Bladder Neoplasm",
        "Bladder Tumor",
        "Bladder Neoplasm",
        "Malignant Tumor of Urinary Bladder",
        "Cancer of the Bladder",
        "Bladder Cancer",
        "Cancer of Bladder"
        # Kidney (Renal Cell) Cancer
        "Nephroid Carcinoma",
        "Adenocarcinoma Of Kidney",
        "Renal Cell Carcinoma",
        "Renal Cell Cancer",
        "Renal Adenocarcinoma",
        "Renal Carcinoma",
        "Renal Cell Adenocarcinoma",
        "Grawitz Tumor",
        "Hypernephroid Carcinoma",
        "Collecting Duct Carcinoma of the Kidney",
        "Renal Collecting Duct Carcinoma",
        # Penile Cancer
        "Penis Neoplasm",
        "Penile Neoplasm",
        "Cancer of Penis",
        "Cancer of the Penis",
        "Penis Cancer",
        "Penile Cancer",
        # Prostate Cancer
        "Prostate Neoplasm",
        "Prostatic Neoplasm",
        "Prostate Cancer",
        "Cancer of the Prostate",
        "Prostatic Cancer",
        "Cancer of Prostate"
        # Renal Pelvis and Ureter Cancer, Transitional Cell
        "Transitional Cell Carcinoma",
        # Testicular Cancer
        "Testicular Neoplasm",
        "Testis Neoplasm",
        "Testicular Tumor",
        "Cancer of Testis",
        "Testis Cancer",
        "Cancer of the Testes",
        "Cancer of the Testis",
        "Testicular Cancer",
        "Tumor of Rete Testis",
        "Rete Testis Tumor",
        "Testis Tumor, Rete",
        "Leydig Cell Tumor",
        "Sertoli Cell Tumor",
        # Urethral Cancer
        "Urethra Neoplasm",
        "Urethral Neoplasm",
        "Cancer of Urethra",
        "Urethra Cancer",
        "Urethral Cancer",
        "Cancer of the Urethra"
        # Cervical Cancer
        "Uterine Cervical Neoplasm",
        "Cervical Neoplasm",
        "Cervix Neoplasm",
        "Cancer of the Uterine Cervix",
        "Cancer of the Cervix",
        "Cervical Cancer",
        "Uterine Cervical Cancer",
        "Cancer of Cervix",
        "Cervix Cancer",
        # Endometrial Cancer
        "Endometrial Neoplasm",
        "Endometrial Carcinoma",
        "Endometrial Cancer",
        "Endometrium Cancer",
        "Cancer of the Endometrium",
        "Carcinoma of Endometrium",
        "Endometrium Carcinoma",
        "Cancer of Endometrium",
        "Endometrium Cancers",
        "Endometrial Stromal Tumors",
        "Carcinoma, Endometrioid",
        # Fallopian Tube Cancer
        "Fallopian Tube Neoplasm",
        "Fallopian Tube Cancer",
        "Cancer of the Fallopian Tube",
        # leukemia
        "Leukemia",
        "Leucocythaemia",
        "Leucocythemia",
        # Acute Lymphoblastic Leukemia
        "Acute Lymphoblastic Leukemia",
        "Acute Lymphocytic Leukemia",
        "Acute Lymphoid Leukemia",
        " ALL ",
        # Acute Myeloid Leukemia
        "Acute Myeloid Leukemia",
        "Acute Myeloblastic Leukemia",
        "Acute Myelocytic Leukemia",
        "Acute Nonlymphoblastic Leukemia",
        "Acute Nonlymphocytic Leukemia",
        "Acute Myelogenous Leukemia",
        " AML "
        # Chronic Lymphocytic Leukemia
        "Small-Cell Lymphoma",
        "Small Cell Lymphoma",
        "Chronic Lymphocytic Lymphoma",
        "Chronic Lymphoblastic Leukemia",
        "Chronic B-Cell Leukemia",
        "Chronic Lymphocytic Leukemia",
        "Chronic Lymphatic Leukemia",
        "Small Lymphocytic Lymphoma",
        " CLL ",
        # Chronic Myelogenous Leukemia
        "Chronic Granulocytic Leukemia",
        "Chronic Myeloid Leukemia",
        "Chronic Myelocytic Leukemia",
        "Chronic Myelogenous Leukemia",
        " CML ",
        # Hodgkin Lymphoma
        "Hodgkin's Granuloma",
        "Hodgkins Granuloma",
        "Malignant Lymphogranuloma",
        "Hodgkin Lymphoma",
        "Hodgkin's Disease",
        "Hodgkin's Lymphoma",
        "Hodgkins Lymphoma",
        "Hodgkins Disease",
        "Hodgkin Granuloma",
        # Mycosis Fungoides
        "Mycosis Fungoides",
        "Pagetoid Reticulosis",
        # Non-Hodgkin Lymphoma
        "Diffuse Small Cleaved-Cell Lymphoma",
        "Diffuse Small Cleaved Cell Lymphoma",
        "Non-Hodgkins Lymphoma",  # how do we deal with hodgkin's and non-hodgkin's on regex? only include hyphen and accept above includes nonhodgkin's?
        "Non-Hodgkin's Lymphoma",
        "Non Hodgkin's Lymphoma",
        "Non-Hodgkin Lymphoma",
        "Non Hodgkin Lymphoma",
        "Burkitt Lymphoma",
        # Sézary Syndrome
        "Sezary's Lymphoma",
        "Sezary Lymphoma",
        "Sezarys Lymphoma",
        "Sezary Erythroderma",
        # Waldenström Macroglobulinemia
        "Lymphoplasmacytoid Lymphoma",
        "Waldenstrom's Macroglobulinemia",
        "Waldenstroms Macroglobulinemia",
        "Waldenstrom's Macroglobulinaemia",
        "Waldenstrom Macroglobulinaemia",
        "Waldenstroms Macroglobulinaemia",
        # Langerhans Cell Histiocytosis
        "Hand-Schueller-Christian Syndrome",
        "Hand Schueller Christian Syndrome",
        "Hand-Schüller-Christian Disease",
        "Hand Schüller Christian Disease",
        "Hand-Schüller-Christian Syndrome",
        "Hand Schüller Christian Syndrome",
        "Histiocytosis X",
        "Generalized Histiocytoses",
        "Generalized Histiocytosis",
        "Histiocytoses, Generalized",
        "Histiocytosis-X",
        "Langerhans Cell Histiocytosis",
        "Langerhans Cell Histiocytoses",
        "Langerhans-Cell Granulomatosis",
        "Langerhans-Cell Histiocytosis",
        "Letterer-Siwe Disease",
        "Letterer Siwe Disease",
        "Schueller-Christian Disease",
        "Schueller Christian Disease",
        "Type 2 Histiocytosis",
        "Type 2 Histiocytoses",
        "Langerhans Cell Granulomatosis",
        "Langerhans Cell Granulomatoses",
        "Hand-Schueller-Christian Disease",
        "Hand Schueller Christian Disease",
        # Myelodysplastic Syndromes
        "Myelodysplastic Syndrome",
        "Dysmyelopoietic Syndrome",
        "Myelodysplasia",
        # hematologic neoplasms
        "Hematologic Neoplasm",
        "Hematologic Malignancies",
        "Hematologic Malignancy",
        "Hematological Neoplasm",
        "Blood Cancer",
        "Hematological Malignancy",
        "Hematopoietic Neoplasm",
        "Hematopoietic Malignancies",
        "Hematopoietic Malignancy",
        "Bone Marrow Neoplasm",
        "Primary Polycythemia",
        "Polycythemia Rubra Vera",
        "Polycythemia Ruba Vera",
        "Osler-Vaquez Disease",
        "Osler Vaquez Disease"
        # Bone Cancer
        "Bone Neoplasm",
        "Bone Cancer",
        "Cancer of the Bone",
        "Cancer of Bone",
        "Adamantinomas",
        "Adamantinoma"
        # Ewing Sarcoma
        "Ewing's Sarcoma",
        "Ewings Sarcoma",
        "Ewing's Tumor",
        "Ewings Tumor",
        "Ewing Sarcoma",
        "Ewing Tumor",
        # Osteosarcoma and Undifferentiated Pleomorphic Sarcoma of Bone Treatment
        "Osteosarcomas",
        "Osteosarcoma Tumor",
        "Osteosarcoma Tumors",
        "Sarcoma, Osteogenic",
        "Osteogenic Sarcomas",
        "Osteogenic Sarcoma",
        "Osteosarcoma, Juxtacortical",
        # Chordoma
        "Chordoma",
        # Rhabdomyosarcoma
        "Rhabdomyosarcomas",
        # Soft Tissue Sarcoma
        "Soft Tissue Sarcoma",
        "Soft Tissue Sarcomas",
        "Epithelioid Sarcoma",
        "Epithelioid Sarcomas",
        "Spindle Cell Sarcoma",
        "Spindle Cell Sarcomas"
        # Brain Tumor
        "Brain Neoplasm",
        "Brain Tumour",
        "Brain Tumor",
        "Intracranial Neoplasm",
        "Brain Metastase",
        "Brain Cancer",
        "Cancer of Brain",
        "Cancer of the Brain",
        "Cerebroventricular Neoplasm",
        "Intraventricular Neoplasm",
        "Cerebral Ventricle Tumor",
        "Brain Ventricular Tumor",
        "Brain Ventricular Neoplasms",
        "Cerebral Ventricle Neoplasm",
        "Choroid Plexus Tumor",
        "Choroid Plexus Neoplasm",
        "Primary Choroid Plexus Neoplasms",
        "Choroid Plexus Papillomas",
        "Papilloma of Choroid Plexus",
        "Choroid Plexus Papilloma",
        "Infratentorial Neoplasm",
        "Posterior Fossa Tumor",
        "Infratentorial Tumor",
        "Posterior Fossa Neoplasm",
        "Infratentorial Cancer",
        "Brain Stem Neoplasm",
        "Brainstem Neoplasm",
        "Brainstem Tumor",
        "Brain Stem Tumor",
        "Pontine Tumor",
        "Pontine Neoplasm",
        "Mesencephalic Neoplasm",
        "Midbrain Tumor",
        "Midbrain Neoplasm",
        "Medullary Neoplasm",
        "Medullary Tumor",
        "Cerebellar Tumor",
        "Cerebellar Tumour",
        "Cerebellar Neoplasm",
        "Cerebellar Cancer",
        "Cerebellar Cancers",
        "Neurocytomas",
        "Central Neurocytoma",
        "Pinealomas",
        "Pineal Gland Tumor",
        "Pineal Tumors",
        "Pineal Tumor",
        "Pineal Neoplasm",
        "Pineoblastoma",
        "Pinealocytoma",
        "Pineocytoma",
        "Supratentorial Tumor",
        "Supratentorial Neoplasm",
        "Supratentorial Cancer",
        "Hypothalamus Neoplasm",
        "Hypothalamus Tumor",
        "Hypothalamic Tumor",
        "Hypothalamic Neoplasm",
        "Hypothalamic Cancer",
        "Hypothalamic Teratoma",
        # Astrocytomas
        "Astroglioma",
        "Astrocytic Glioma",
        "Astrocytoma",
        "Glioblastoma",
        # Brain Stem Glioma
        "Gliomas",
        "Glial Cell Tumors",
        "Glial Cell Tumor",
        "Mixed Glioma",
        "Mixed Gliomas",
        "Malignant Glioma",
        "Malignant Gliomas"
        # Central Nervous System Atypical Teratoid/Rhabdoid Tumor
        "Rhabdoid Tumors",
        "Teratomas",
        "Dysembryoma",
        "Teratoid Tumor",
        # Medulloblastoma and Other Central Nervous System Embryonal Tumors
        "Medulloblastoma",
        # Craniopharyngioma
        "Craniopharyngiomas",
        "Rathke's Pouch Tumor",
        "Rathkes Pouch Tumor",
        "Rathke Pouch Tumor",
        "Rathke's Cleft Neoplasm",
        "Rathkes Cleft Neoplasm",
        "Rathke Cleft Neoplasm",
        # Ependymoma
        "Ependymomas",
        # Neuroblastoma
        "Neuroblastomas",
        "Ganglioneuroblastoma",
        # Lung Cancer, Non-Small Cell
        "Non-Small-Cell Lung Carcinomas",
        "Non-Small-Cell Lung Carcinoma",
        "Non Small Cell Lung Carcinoma",
        "Non-Small Cell Lung Carcinoma",
        "Non-Small Cell Lung Cancer",
        "Nonsmall Cell Lung Cancer",
        # Lung Cancer, Small Cell
        "Small Cell Lung Cancer",
        "Small Cell Cancer of the Lung",
        "Oat Cell Lung Cancer",
        "Oat Cell Carcinoma",
        # Malignant Mesothelioma
        "Malignant Mesothelioma",
        "Malignant Pleural Mesothelioma",
        # Thymoma and Thymic Carcinoma
        "Thymomas",
        "Thymic Carcinoma",
        # T-Cell Lymphoma, Cutaneous
        "Cutaneous T-Cell Lymphoma",
        "Cutaneous T Cell Lymphoma",
        # neoplasms, unknown primary
        "Occult Primary Neoplasms",
        "Occult Primary Neoplasm",
        "Primary Neoplasms, Occult",
        "Unknown Primary Neoplasms",
        "Unknown Primary Neoplasm",
        "Unknown Primary Tumors",
        "Unknown Primary Tumor",
        "Unknown Primary Neoplasm Metastasis"
        # Melanoma
        "Melanomas",
        "Malignant Melanoma",
        "Malignant Melanomas",
        # Skin Cancer
        "Skin Neoplasm",
        "Cancer of Skin",
        "Cancer of the Skin",
        "Skin Cancer",
        "Acanthoma",
        "Muir-Torre Syndrome",
        "squamous cell carcinoma",
        "basal cell carcinoma",
        "melanoma",
        # Anal Cancer
        "Anal Neoplasm",
        "Anus Neoplasm",
        "Anal Cancer",
        "Cancer of the Anus",
        "Cancer of Anus",
        "Anus Cancer",
        # Appendix Cancer
        "Appendiceal Neoplasm",
        "Appendiceal Cancer",
        "Cancer of the Appendix",
        "Appendix Cancer",
        "Cancer of Appendix"
        # Bile Duct Cancer
        "Bile Duct Neoplasm",
        "Bile Duct Cancer",
        "Cancer of the Bile Duct",
        "Cancer of Bile Duct"
        # Colon Cancer
        "Colonic Neoplasm",
        "Colon Neoplasm",
        "Cancer of Colon",
        "Colon Cancer",
        "Cancer of the Colon",
        "Colonic Cancer",
        "Colonic Cancers",
        "Colon Adenocarcinoma",
        "Colon Adenocarcinomas",
        "appendiceal carcinoma" "sigmoid carcinoma",
        "ileocecal carcinoma",
        "cecal carcinoma",
        "rectosigmoid carcinoma",
        "rectal carcinoma",
        "rectal adenocarcinoma",
        # Esophageal Cancer
        "Esophageal Neoplasm",
        "Esophagus Neoplasm",
        "Cancer of Esophagus",
        "Cancer of the Esophagus",
        "Esophagus Cancer",
        "Esophageal Cancer",
        "Esophageal Squamous Cell Carcinoma",
        # Gallbladder Cancer
        "Gallbladder Neoplasm",
        "Cancer of Gallbladder",
        "Gallbladder Cancers",
        "Gallbladder Cancer",
        "Gall Bladder Cancer",
        "Gall Bladder Cancers",
        "Cancer of the Gallbladder",
        "Cholangiocarcinoma"
        # Gastrointestinal Stromal Tumors (GIST)
        "Gastrointestinal Stromal Neoplasms",
        "Gastrointestinal Stromal Tumor",
        "Gastrointestinal Stromal Neoplasm",
        "Gastrointestinal Stromal Sarcoma"
        # Islet Cell Tumors, Pancreatic Neuroendocrine Tumors
        "Islet Cell Adenoma",
        "Islet Cell Tumor",
        "Islet of Langerhans Tumor",
        "Island Cell Tumor",
        "Nesidioblastoma",
        # Liver Cancer
        "Liver Neoplasm",
        "Hepatic Neoplasm",
        "Cancer of Liver",
        "Hepatocellular Cancer",
        "Hepatocellular Cancers",
        "Hepatic Cancer",
        "Hepatic Cancers",
        "Liver Cancer",
        "Liver Cancers",
        "Cancer of the Liver",
        # Pancreatic Cancer
        "Pancreatic Neoplasm",
        "Pancreas Neoplasm",
        "Cancer of Pancreas",
        "Pancreas Cancer",
        "Pancreatic Cancer",
        "Cancer of the Pancreas",
        "Insulinoma",
        "Gastrinoma",
        "Glucagonoma",
        "Somatostatinoma",
        "Vipoma",
        "Pancreatic Intraductal Neoplasm"
        # Stomach (Gastric) Cancer
        "Stomach Neoplasm",
        "Gastric Neoplasm",
        "Cancer of Stomach",
        "Gastric Cancer",
        "Stomach Cancer",
        "Cancer of the Stomach",
        "Gastric Cancer, Familial Diffuse",
    ]
]
